### PR TITLE
YAML surface phase requires kinetics model

### LINKED ISSUE #1244: YAML surface phase requires kinetics model
**Problem description**

For bulk phases, the default behavior if no `kinetics` field is specified in the YAML phase definition is to just instantiate the base `Kinetics` class. However, this does not work for interface phases.

**Steps to reproduce**

For the YAML input (say, `test.yaml`):
```yaml
phases:
- name: test
  thermo: ideal-surface
  species: [{ptcombust.yaml/species: all}]
  state: {T: 300, P: 1 atm}
```
Importing in Python yields the exception:
```py
p = ct.Solution("test.yaml")

File build/python/cantera/base.pyx:63, in cantera._cantera._SolutionBase.__cinit__()

File build/python/cantera/base.pyx:120, in cantera._cantera._SolutionBase._cinit()

File build/python/cantera/base.pyx:207, in cantera._cantera._SolutionBase._init_yaml()

CanteraError: 
*******************************************************************************
CanteraError thrown by Interface::setKinetics:
Kinetics object of type 'None' does not descend from InterfaceKinetics.
*******************************************************************************
```
Trying to load with `ct.Interface` yields the same exception.

In Cantera 2.5.1, loading the phase with `ct.Solution` worked, while using `ct.Interface` failed with the exception:
```
TypeError: Underlying Kinetics class is not of the correct type.
```

I expect that the same issue would occur using the C++ `newInterface()` constructor.

**System information**

- Cantera version: 2.6.0b2 / e7b931b2a
- OS: macOS 12.2, though I assume this is universal
- Python/MATLAB/other software versions: Python 3.10

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

- Make default kinetics type dependent on phase dimensions

**If applicable, fill in the issue number this pull request is fixing**

Closes #1244

**If applicable, provide an example illustrating new features this pull request is introducing**

*updated ...*

For the YAML input (say, `test.yaml`):
```yaml
phases:
- name: test
  thermo: ideal-surface
  species: [{ptcombust.yaml/species: all}]
  state: {T: 300, P: 1 atm}
```
Importing in Python yields:

```
>>> import cantera as ct
>>> p = ct.Interface("test.yaml")
>>> p.reactions()
[]
>>> p.species_names
['PT(S)', 'H(S)', 'H2O(S)', 'OH(S)', 'CO(S)', 'CO2(S)', 'CH3(S)', 'CH2(S)s', 'CH(S)', 'C(S)', 'O(S)']
```

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by speth** [comment]
> ```yaml
> phases:
> - name: test
>   thermo: ideal-surface
>   species: [{ptcombust.yaml/species: all}]
>   reactions: none
>   state: {T: 300, P: 1 atm}
> ```

I think the goal should be to allow the construction of a `Solution` or `InterfacePhase` object, and probably an `Interface` without having to specify anything about the kinetics or reactions. The behavior here is actually a bit surprising -- we currently regard specifying a `reactions` key without a `kinetics` key as an error, and I think that behavior should probably be maintained (at least, as long as the idea of having different kinetics models lasts).

**Comment by ischoegl** [comment]
@speth … thanks for your comment!

I actually had originally implemented a version that didn’t require `reactions: none`, but opted for a simpler version that didn’t need a logic change. Based on your comment, I added things back in, ~which does change one example in the test suite.~

**Comment by ischoegl** [comment]
@speth ... I believe this is ready for review.

**Review by speth — APPROVED** [review]
Thanks, this looks good to me. I think the bit of extra implementation complexity is worth it for the more straightforward end-user experience.

**Pull request merged**
