### PR TITLE
Adding faradayconstant.m to Matlab toolbox

### PR DESCRIPTION
**Pull request by decaluwe**
Changes proposed in this pull request:
- Adds a function `faradayconstant.m` to the Matlab toolbox which, akin to `gasconstant.m`, returns the value of the Faraday constant, in Coulombs per kmol of electron.

### CODE REVIEW

**Comment by bryanwweber** [comment]
Can you get this number from the built-in constants? Would it be possible to create a Matlab class that has all of the constants that Cantera defines?

**Comment by decaluwe** [comment]
C’mon, man, you’re ruining my “easiest PR ever!” 😂

**Comment by bryanwweber** [comment]
If the answer to either of those is "its complicated", I'm fine with this as-is. But if its easy... why not, you know?

**Comment by speth** [comment]
This is consistent with how other constants are currently defined in the Matlab toolbox, so I think this is fine as-is. I'd save anything more complicated for the long overdue rewrite of the Matlab toolbox.

**Pull request merged**
