### PR TITLE
Backport bugfixes from main to 2.5

### PR DESCRIPTION
**Pull request by bryanwweber**
**Changes proposed in this pull request**

- Backport several bug fixes from the `main` branch to `2.5`:
  - ccc216d
  - [`ae7734a..c6ff662`](https://github.com/Cantera/cantera/compare/ae7734a...c6ff662)
  - 908a2cc
  - a4b9bb5
  - [`9644788^..b42989f`](https://github.com/Cantera/cantera/compare/9644788%5E...b42989f)
  - 388f03c
  - [`70f3530^..b3c69ac`](https://github.com/Cantera/cantera/compare/70f3530%5E...b3c69ac)

**Checklist**

- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by ischoegl** [comment]
@bryanwweber ... would it make sense to add a fix for #1009?

**Comment by bryanwweber** [comment]
@ischoegl sure, if a fix for #1009 gets merged to `main` before we close this PR. The `2.5` branch is meant as the release branch, so to collect all the relevant minor fixes... Speaking of which, I should probably bump to 2.5.2a1

Edit to add: on second thought, it might not make sense to include if reproducing the bug relies on deprecated code that's only been removed in 2.6

**Comment by speth** [comment]
For doing a version bump on this branch, I'd suggest `2.5.2b1` - I think anything that gets cherry-picked here ought to be simple and stable enough that this is never an "alpha".

**Comment by bryanwweber** [comment]
Merged in https://github.com/Cantera/cantera/commit/cdc9f7042c3dd4e249cd806228078cadaad64b4d

**Pull request closed without merging**
