### PR TITLE
Update License.txt

### PR DESCRIPTION
**Pull request by ischoegl**
Happy 2020, everyone!

### CODE REVIEW

**Comment by speth** [comment]
:tada: The copyright in `doc/sphinx/conf.py` also needs to be updated. I think those are the only two in this repo.

**Comment by ischoegl** [comment]
@bryanwweber ... this code coverage diff is even more interesting. I have no idea what's happening here.

**Comment by bryanwweber** [comment]
I think maybe what happens is that the comparison is done to `master` at the time when the PR is opened and then that same commit is used even if the base commit of the branch is updated (e.g., rebase after master is updated) 🤷‍♂️ that would hypothetically explain the behavior here I think

**Comment by speth** [comment]
Funny, it just updated itself again, and now the coverage looks fine (the fix for the oscillation in `HMWSoln.cpp` is in #773.

**Review by speth — APPROVED** [review]

**Pull request merged**
