### PR TITLE
[CI] Remove ubuntu-18.04 and add ubuntu-22.04

### LINKED ISSUE #1370: GH runners for ubuntu 18.04 are deprecated
**Problem description**

Github runners for Ubuntu 18.04 will be retired by 12/1/2022, as only two stable versions will be supported.

Per upstream https://github.com/actions/runner-images/issues/6002, there are numerous brownouts scheduled between 8/22 and the 12/1/2022 deadline (when support will be removed).

In order to avoid disruption, at least some (or all?) runners should be updated.

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

Update GitHub actions:

- Remove `ubuntu-18.04` (faces brownouts in deprecation period and will be removed in December)
- Add `ubuntu-22.04`

**If applicable, fill in the issue number this pull request is fixing**

Closes #1370

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by bryanwweber** [comment]
Looks like the coverage build is broken? Is that related to the changes here?

**Comment by ischoegl** [comment]
> Looks like the coverage build is broken? Is that related to the changes here?

I don't think so, but something about that CI run is odd. Let me retrigger.

**Comment by ischoegl** [comment]
Coverage ran through this time ... (which is a relief, as I hadn't touched that test)

**Review by bryanwweber — APPROVED** [review]
Thanks!

**Pull request merged**
