### PR TITLE
Yaml2ck fixes

### LINKED ISSUE #1633: yaml2ck handles multi-line "note" fields incorrectly
**Problem description**

Multi-line `note` fields in thermo entries are not correctly converted to comment lines by `yaml2ck` -- only the first line has a `!` character added. This causes errors round-tripping thermo files if the original CK file contained commented-out species entries, which are then re-inserted without being marked as comments.

**Steps to reproduce**

Use `yaml2ck` to convert a file containing the following species entry:

```yaml
- name: CH3OCO
  composition: {H: 3, C: 2, O: 2}
  thermo:
    model: NASA7
    temperature-ranges: [200.0, 1000.0, 3000.0]
    data:
    - [6.42720143, -7.97126399e-03, 5.91518706e-05, -6.98220041e-08, 2.64882011e-11,
      -2.1166004e+04, -0.784719994]
    - [4.11346455, 0.017235061, -9.1563172e-06, 2.30732677e-09, -2.2553008e-13,
      -2.13756201e+04, 6.78109955]
    note: |-
      !DHf(0K) =     9.73 [kcal/mol], taken from SJK v0.9.
      !Q(T) from B3LYP/6-311++G(d,p) by CFG on  06Sep2013
      HCO                     H  1 C  1 O  1      G   200.0   3000.0   1000.0        1
       2.54295623E+00 5.31270712E-03-2.75965333E-06 6.86785548E-10-6.66794809E-14    2
       3.99103060E+03 1.10699925E+01 4.17956080E+00-2.85097257E-03 1.25531492E-05    3
      -1.21627661E-08 3.99714476E-12 3.73162143E+03 3.53923487E+00                   4
      DHf(0K) =   -36.23 [kcal/mol], taken from SJK v0.9.
      Q(T) from B3LYP/6-311++G(d,p) by CFG on  06Sep2013
```

**Behavior**

Resulting section of generated CK thermo file:
```
!!DHf(0K) =     9.73 [kcal/mol], taken from SJK v0.9.
!Q(T) from B3LYP/6-311++G(d,p) by CFG on  06Sep2013
HCO                     H  1 C  1 O  1      G   200.0   3000.0   1000.0        1
 2.54295623E+00 5.31270712E-03-2.75965333E-06 6.86785548E-10-6.66794809E-14    2
 3.99103060E+03 1.10699925E+01 4.17956080E+00-2.85097257E-03 1.25531492E-05    3
-1.21627661E-08 3.99714476E-12 3.73162143E+03 3.53923487E+00                   4
DHf(0K) =   -36.23 [kcal/mol], taken from SJK v0.9.
Q(T) from B3LYP/6-311++G(d,p) by CFG on  06Sep2013
CH3OCO                  C   2H   3O   2     G200.000   3000.000  1000.000      1
 4.11346455E+00 1.72350610E-02-9.15631720E-06 2.30732677E-09-2.25530080E-13    2
-2.13756201E+04 6.78109955E+00 6.42720143E+00-7.97126399E-03 5.91518706E-05    3
-6.98220041E-08 2.64882011E-11-2.11660040E+04-7.84719994E-01                   4
```

**System information**

- Cantera version: 3.0.0 (conda-forge package)
- OS: macOS 13.5.1
- Python/MATLAB/other software versions: Python 3.11 (conda-forge)

**Additional context**

Discovered while investigating #1632.

### LINKED ISSUE #1679: yaml2ck fails for phases with no reactions
**Problem description**

Trying to convert a YAML mechanism to CK format fails when the phase has no reactions.

**Steps to reproduce**

1. Download attached `org.yaml.txt` and save as `org.yaml`
2. From a command prompt, run `yaml2ck --mechanism=chem.inp --thermo=therm.dat --overwrite org.yaml`

**Behavior**

`yaml2ck` fails with the following error:

```pytb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "R:\ray\mamba\ctdev312\Lib\site-packages\cantera\yaml2ck.py", line 856, in <module>
    main()
  File "R:\ray\mamba\ctdev312\Lib\site-packages\cantera\yaml2ck.py", line 807, in main
    output_paths = convert(
                   ^^^^^^^^
  File "R:\ray\mamba\ctdev312\Lib\site-packages\cantera\yaml2ck.py", line 704, in convert
    mechanism_text.append(build_reactions_text(all_reactions))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\ray\mamba\ctdev312\Lib\site-packages\cantera\yaml2ck.py", line 356, in build_reactions_text
    max_reaction_length = max(len(r.equation) for r in reactions)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
```

**System information**

- Cantera version: 3.0.0 or `main` branch at 64ed2b732
- OS: Windows 11
- Python/MATLAB/other software versions: Python 3.12 (conda-forge)

**Attachments**

[org.yaml.txt](https://github.com/Cantera/cantera/files/14629510/org.yaml.txt)

**Additional context**

Originally reported on the [Cantera Users' Group](https://groups.google.com/g/cantera-users/c/pax4W_t_qpU)

### PR DESCRIPTION
**Pull request by corykinney**
**Changes proposed in this pull request**

This pull request would fix a couple of issues with `yaml2ck`:

- Multi-line species thermo notes now have the comment marker `!` at the beginning of each line
- Writing a phase with no reactions will no longer crash, as the `REACTIONS` section is omitted

**If applicable, fill in the issue number this pull request is fixing**

Closes #1633 and closes #1679

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

### CODE REVIEW

**Comment by corykinney** [comment]
Should I implement test cases for these, or are these changes simple and straightforward enough as it is?

**Comment by speth** [comment]
> Should I implement test cases for these, or are these changes simple and straightforward enough as it is?

They're simple changes, but I think some test cases would be useful to prevent any inadvertent regression in behavior.

**Comment by corykinney** [comment]
@speth Okay, I think the test cases added should be sufficient (and I've confirmed they fail apart from the changes implemented, so they should address what they were intended to). 

EDIT: For the phase with no reactions test, it only checks the Chemkin file was written, should that be enough?

**Review by speth — APPROVED** [review]
This looks good to me. Thanks for fixing these problems, @corykinney.

**Pull request merged**
