### PR TITLE
Address fmt::format_to memory_buffer deprecation

### LINKED ISSUE #1098: Upcoming fmt::format_to memory_buffer deprecation
**Problem description**

An upstream deprecation in `fmtlib` deprecated `format_to` `memory_buffer`, which is used sporadically in Cantera and triggers a slew of deprecation warnings for recent fmtlib versions (see log posted in #1095) . For a discussion of replacement options, see https://github.com/fmtlib/fmt/issues/2420. 

**Steps to reproduce**

See log posted in #1095

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

The deprecation is addressed by replacing
```c++
fmt::memory_buffer b;
format_to(b, "The answer is {}.", 42);
```
by
```c++
fmt::memory_buffer b;
format_to(std::back_inserter(b), "The answer is {}.", 42);
```

The fix uses `std::back_inserter` rather than `fmt::appender` as the latter is not available in older versions of `libfmt`. The current GH Actions Sundials runners already use `libfmt v8.0.1` where the deprecation warnings show up.

Also reformatted affected lines to stay within the 88 character line limits.

**If applicable, fill in the issue number this pull request is fixing**

Closes #1098

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by bryanwweber** [comment]
> as the latter is not available in older versions of `libfmt`

What's the oldest version that has `fmt::appender`? We could consider bumping the minimum version of libfmt.

**Comment by ischoegl** [comment]
> What's the oldest version that has `fmt::appender`? 

Hard to tell ... `fmt::appender` is implied to be preferable over `std::back_inserter` in fmtlib/fmt#2420, but it is also pointed out that it is undocumented (at least on their [official documentation](https://fmt.dev/latest/index.html)). It certainly isn't part of `fmt v6.2.1` which is stock Ubuntu 18.04. There's also no information to be gleaned from the [release notes](https://github.com/fmtlib/fmt/releases).

**Comment by speth** [comment]
Writing `format_to(std::back_inserter(b), ...)` every time gets a little clunky. I wouldn't be opposed adding a simple utility function like
```c++
template <typename... Args>
void fmt_append(fmt::memory_buffer& b, Args... args) {
    format_to(std::.back_inserter(b), args...);
}
```
which probably belongs in `include/cantera/base/fmt.h`. If you look in that file, you may notice that this isn't the first time that the API for building up a formatted string this way has changed -- we have a workaround to implement `format_to` using the API that was used before version 5.0.

**Comment by ischoegl** [comment]
@speth ... thanks for the comment. There are pro's and con's to both options:

* pro of `format_to(std::back_inserter(b), ...)` is that it uses `fmt` directly / con is that it's clunky and doesn't allow `fmt::appender`
* pro of the template is that it's more flexible (we get to differentiate between `fmt` versions) / con is that it's no longer a standard `fmt` function.

I don't have a strong preference here.

**Comment by ischoegl** [comment]
OK. I added the template version in a separate commit (i.e. should be squashed), where I used `fmt::appender` (introduced in `v8.0.0`). Also fixed a minor compilation warning that I noticed.

_PS: I noticed a couple of minor alignment glitches, which I'll fix when squashing._

**Comment by ischoegl** [comment]
@speth / @bryanwweber ... done.

**Review by speth — APPROVED** [review]
Thanks, @ischoegl! This looks good to me.

**Pull request merged**
