### PR TITLE
[ext/fmtlib] Bump fmtlib to 6.1.2

### PR DESCRIPTION
**Pull request by bryanwweber**
Thanks for contributing code! Please include a description of your change and
check your PR against the list below (for further questions, refer to the
[contributing guide](https://github.com/Cantera/cantera/blob/master/CONTRIBUTING.md)).

- [X] There is a clear use-case for this code change
- [X] The commit message has a short title & references relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage

**Changes proposed in this pull request**

- Bumps fmtlib/fmt to version 6.1.2, which was released today (Dec. 11, 2019)
- I'm expecting the tests to fail, when I was testing for #722 I was using fmtlib 6.1.0 and the output in several places had dropped a decimal point (i.e., 1.0000e+02 became 10000e+02). The changes went away when I dropped back to fmtlib 5.0.0, so I surmise the cause is an updated function in fmtlib. This PR is mainly here to develop a fix for this problem.

### CODE REVIEW

**Comment by speth** [comment]
I noticed this as well while trying out some other new features in `fmtlib` the other day. It appears to be a problem in 6.1.0 that was fixed in 6.1.1 (see https://github.com/fmtlib/fmt/commit/8bbe76af3a5427597185ad6207ee6e588d2eb0fd).

**Comment by bryanwweber** [comment]
@speth Good to know, it's listed right in the release notes. Is this bump worth merging and if so, should we have SCons produce a useful error message for fmt 6.1.0?

**Comment by speth** [comment]
6.1.0 lasted as the current release for all of 4 days. A specific check for that seems unnecessary.

**Comment by bryanwweber** [comment]
And somehow I managed to end up with it from Hombrew... Point taken, is this PR worth merging or should it just be closed?

**Comment by speth** [comment]
🤷‍♂ Your call. We should probably update this at some point, but I'd also like to make sure that we're testing with at least one older version. A reasonable target for this would be fmt 4.0.0, which is what is in Ubuntu 18.04.

**Comment by bryanwweber** [comment]
Sure. I started setting up an Azure Pipelines instance to run more of these kinds of tests in parallel.

**Pull request merged**
