### PR TITLE
Bump version to 2.6.0b1

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

Creating this PR in anticipation of #1158 being merged.

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by bryanwweber** [comment]
> Bump version to 2.5.0b1

2.6.0b1? The actual changes are correct, just typos in the title and commit message 😄

**Comment by ischoegl** [comment]
whoops.

**Comment by ischoegl** [comment]
Should probably also be applied after #1222 ... (and whatever else is in the works)

**Review by speth — APPROVED** [review]
I think it's beta time! 🎉

**Pull request merged**
