### PR TITLE
fixed slicing of SolutionArray

### LINKED ISSUE #804: Slicing of SolutionArray raises error
**System information**

- Cantera version: 2.5.0a4
- OS: Ubuntu
- Python/MATLAB version: Python 3.6.8

**Expected behavior**

Slicing of `SolutionArray` objects should work as usual (as indexing is implemented).

**Actual behavior**

Slicing does not work.

**To Reproduce**

```
In [1]: import cantera as ct
   ...: gas = ct.Solution('gri30.yaml')
   ...: arr = ct.SolutionArray(gas, 10)

In [2]: arr[0]
Out[2]: <cantera.composite.SolutionArray at 0x7ffa61a364e0>

In [3]: arr[:]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-47ed00660ce3> in <module>()
----> 1 arr[:]

/usr/local/lib/python3.6/dist-packages/cantera/composite.py in __getitem__(self, index)
    534     def __getitem__(self, index):
    535         states = self._states[index]
--> 536         shape = states.shape[:-1]
    537         return SolutionArray(self._phase, shape, states)
    538 

AttributeError: 'list' object has no attribute 'shape'
```

**Additional context**

The error message clearly points at the issue.

### PR DESCRIPTION
**Pull request by sin-ha**
**Checklist**
- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] The pull request is ready for review

**If applicable, fill in the issue number this pull request is fixing**

Fixes #804 
The changes allow list slicing in SolutionArray

**Changes proposed in this pull request**

-Changes to accommodate list slicing by making two cases of the SolutionArray

### CODE REVIEW

**Comment by ischoegl** [comment]
Also see 2f8f68554758b152e76cc7b68d65514988da948e :wink:

**Comment by bryanwweber** [comment]
@ischoegl Can you clarify if that is part of a particular PR or is it merged to master? If merged to master, why is #804 still open? Thanks

**Comment by ischoegl** [comment]
@bryanwweber ... the commit I referenced is part of #805, which is awaiting review. I stumbled across this while working on #805 and submitted an issue then. 

I don't have a problem with @sin-ha's resolution, as it is virtually identical (#805 does depend on slicable SolutionArrays though, so the fix should be applied first in whichever way).

**Comment by ischoegl** [comment]
Done.

Looks like everyone's busy these days?

**Comment by sin-ha** [comment]
hey, @ischoegl @bryanwweber  I am eager to work on related problems can you guide me? on #805

**Comment by ischoegl** [comment]
@sin-ha ... pull request #805 is currently awaiting review by one of the developers, so there's nothing to do there apart from reviewing.

For things to work on, the issue tracker is a good start. Look for open issues that do not have a linked pull request yet (you should see an icon on the overview; linked pull requests contain proposed fixes). You probably already read through the contributor's guide.

**Pull request merged**
