### PR TITLE
Doublereal fix

### PR DESCRIPTION
**Pull request by wandadars**
Please fill in the issue number this pull request is fixing:

Fixes #

Changes proposed in this pull request:
- Changed all Cantera source files that used doublereal to use double
- Did not change the files in ext as they are external modules
- Left the original typedef in include/cantera/base/config.h defined

I used the following command to recursively find and replace all instances of doublereal with double in all files except fortran files. I went into each directory and performed the operation to prevent it from ever entering the .git directory and possibly corrupting the repo. I know it's probably a terrible idea to do something like this. I just wanted to see if it would work. The results from 'scons build' and 'scons test' were promising as there were no compilation issue and all tests passed.

 find . -type f \( -iname "*" ! -iname ".F*" -or -iname ".f*" \) -print0 | xargs -0 sed -i 's/doublereal/double/g'

### CODE REVIEW

**Comment by speth** [comment]
I agree that the `doublereal` typedef is a bit of a wart in the Cantera source, but I think trying to remove it wholesale will have substantial undesirable consequences. In particular, this will create nasty merge conflicts for any non-trivial branch currently in existence.

I appreciate the enthusiasm, but before putting effort into refactoring the code, I think you should probably discuss any ideas you have with the developers to make sure they aren't things that we have already considered and decided not to do for one reason or another.

**Comment by wandadars** [comment]
Thanks Ray. You're absolutely right. The thought crossed my mind about making a post/question about the doublereal issue. I thought it would be a somewhat lengthy undertaking, and I was surprised when I got it to work in 5 minutes. So I put it up here on Github just to document the method. In hindsight creating an issue and documenting my method for the fix there would be better than a PR.

**Comment by bryanwweber** [comment]
@speth Do we have a long-term plan to excise these warts from the code? Can this be done slowly, over a few months/releases? Do we want to encourage people who are fixing up a class to remove `doublereal` while they're working?

**Comment by speth** [comment]
No, there isn't really a plan for doing this. I think it's pretty far down the list of things to do on a benefit to cost ratio (recognizing that the cost isn't in making the change, it's to dealing with effects on existing branches). The one major project that I hope we eventually get to that will require changing all of these types anyway is making things compatible with automatic differentiation, which I expect will require changing a bunch of things to some templated type anyway, rather than `double` or `doublereal`, so I don't see much value in replacing the latter with the former at present.

I think its OK to make local changes that replace `doublereal` with `double`, but I think that the scope should be much narrower than an entire class -- it should really be restricted to the modifications being made where you'd have merge conflicts anyway if there were changes in the same bit of code. While I've done this myself on occasion, I wouldn't want to set it as an expectation for anyone who is submitting a PR to modify more than the minimal amount of code.

**Comment by wandadars** [comment]
@speth I know that there is a 'Projects' tab on the Cantera github. I'm not sure if it's still being updated regularly. I also saw a great post for the GSOC that outlined some projects that students could undertake.  From my perspective as a beginner at Github/open source contributions, having a spot where the goals/desires of the project are listed is a great thing. It helps bridge the gap between the user: "This software is great and I wish I could contribute something to do" and the project: "we need a person with experience in x, y, z to work on this improvement".

**Pull request closed without merging**
