### PR TITLE
1D continuation with Flame Point Control Technique from axbriones

### PR DESCRIPTION
**Pull request by youmengtian**
Fixes #541 

**Changes proposed in this pull request**

- One dimensional continuation techniques (one- and two-point) from axbriones

### CODE REVIEW

**Comment by speth** [comment]
I appreciate the interest in working on this, since I know this is an important feature that Cantera is currently lacking. Can you explain what changes you've made in this PR compared to #541? I can see that this updated PR at least resolves the merge conflicts that would occur with that branch, which is a good starting point.

The most important thing that this needs is some test cases demonstrating that it works as intended, and right now there don't seem to be any additions to the test suite.

**Comment by youmengtian** [comment]
The major change in this issue is similar to #541. The major difference is resolving the merge conflicts. I have tested the code with a python test case for H2/O2, C2H6/O2 and kerosene/air. But I have not made test cases in test_onedim.py. Actually I don't know how to add a normative test case in it.

I will try to change my python code to test case file.

**Comment by speth** [comment]
Can you expand on what it is you don't know about how to add a test case? I can try to provide some guidance if you let me know where you need help. Can you post the test cases you have run externally, perhaps on https://gist.github.com?

**Comment by youmengtian** [comment]
I share a 1d test in gist.github.com 

https://gist.github.com/youmengtian/5cfb5e1c1862215a5019dbff302c5406

The function `f.set_fuel_side_boundary` and `f.set_oxid_side_boundary`  are used to get the internal boundary location with given temperature, I use 0.95*Tmax in this code. Decrease  the internal boundary tempreature until extinction, the Tmax-chi S curve and related flame station can be achieved.

Sorry for my poor English!

**Comment by bryanwweber** [comment]
If this is really just a rebase and fix any merge problems, we need to find a way to give some credit to the original author. If this is a total rewrite and happens to fix the merge problems, then that probably isn't necessary. I'm not sure what the best way to do that is, but I wanted to bring it up early on here to make sure we handle it appropriately.

**Comment by youmengtian** [comment]
Maybe, It's not just rebase and fixes from #541. The flame control tech is studied and used. But the merge code refers to axbriones's code. So do you have some advise for this condition, thank you.

**Comment by speth** [comment]
@youmengtian, is your first commit (with the commit message "add point flame control") based on the work from #541? If so, it is clear that you've done a fair bit of work on it beyond what was in that branch, so it might make sense to list both you and @axbriones as co-authors of that commit.

Rather than merging with the master branch, can you rebase this onto the current master, and eliminate the merge commit?

Thank you for providing the example. I'm finding that the solver fails (takes too many timesteps without converging) once the temperature gets low enough (around 1000 K). Have you looked at what's happening here? Until that point, the results look pretty encouraging.

**Comment by youmengtian** [comment]
Yes, the batch simulation maybe failed  near extinction and ignition points. So various `dT` should be used in the test code, while I use fixed `dT` in it. @speth You mentioned the current master, so you mean that the merge commit should be rebased to the new master header? And should I contact @axbriones for this merge require?

**Comment by speth** [comment]
I don't think you need to contact anyone to do what I'm suggesting. The only thing that makes this slightly tricky is that you've made this PR from your "master" branch rather than the your `1d_continuation` branch. If you don't mind, I can make the necessary rearrangement and push it to your branch. Once that is done, you can reset your local branch to the modified version of `youmengtian/master`.

**Comment by youmengtian** [comment]
@speth Thanks for your suggestion. I'll try myself with your suggestion, looking forward to further help if I have further mistake or difficulty.

**Comment by youmengtian** [comment]
a new pull require #766 is made with @speth 's suggestion

**Comment by ischoegl** [comment]
Superseded by #766.

**Pull request closed without merging**
