### PR TITLE
Fix pressure dependence in IdealSolidSolnPhase::getPartialMolarEnthalpies

### LINKED ISSUE #1080: IdealSolidSolnPhase::getPartialMolarEnthalpies - needs pressure dependence?
**Problem description**
The `getPartialMolarEnthalpies` routine in `IdealSolidSolnPhase` would appear to be missing the required pressure dependence implemented elsewhere in the model.

All other enthalpy (and, by association, chemical potential) calculations involve some form of `(P - Pref)*molarVolume` (where `molarVolume` is of either the phase or the individual species).

`IdealSolidSolnPhase::getPartialMolarEnthalpies` does not:

```
void IdealSolidSolnPhase::getPartialMolarEnthalpies(doublereal* hbar) const
{
    const vector_fp& _h = enthalpy_RT_ref();
    scale(_h.begin(), _h.end(), hbar, RT());
}
```
I think this ought to be replaced with:
```
void IdealSolidSolnPhase::getPartialMolarEnthalpies(doublereal* hbar) const
{
    const vector_fp& _h = enthalpy_RT_ref();
    scale(_h.begin(), _h.end(), hbar, RT());
    double delta_p = (m_Pcurrent - m_Pref);
    for (size_t k = 0; k < m_kk; k++) {
        hbar[k] += delta_p * m_speciesMolarVolume[k];
    }
}
```
**System information**

- Cantera version: 2.6.0a2

Wanted to check if I was missing something, before fixing it.

### PR DESCRIPTION
**Pull request by decaluwe**
**Changes proposed in this pull request**

- Adds proper pressure dependence to IdealSolidSolnPhase::getPartialMolarEnthalpies

**If applicable, fill in the issue number this pull request is fixing**

Closes #1080 

**If applicable, provide an example illustrating new features this pull request is introducing**
 Previously, the partial molar enthalpies had no pressure dependence for this class.  As a check, the sum of partial molar enthalpy times mole fraction should equal the average phase molar enthalpy.  Prior to this change:
```python
import cantera as ct
import numpy as np

gas = ct.Solution('IdealSolidSolnPhaseExample.yaml',"solidSolutionExample")

# At standard pressure: h_mole = sum(X_k*h_k)
h_mole = gas.enthalpy_mole
h_check = np.dot(gas.partial_molar_enthalpies, gas.X)
print(h_mole - h_check)
0

# At non-standard pressure, h_mole shows the correct pressure dependence, but the partial molar enthalpies do not:
gas.TP = None, 3*ct.one_atm
h_mole = gas.enthalpy_mole
h_check = np.dot(gas.partial_molar_enthalpies, gas.X)
print(h_mole, h_check)
303975
```

With the implemented correction:
```python
import cantera as ct
import numpy as np

gas = ct.Solution('IdealSolidSolnPhaseExample.yaml',"solidSolutionExample")

# At standard pressure: h_mole = sum(X_k*h_k)
h_mole = gas.enthalpy_mole
h_check = np.dot(gas.partial_molar_enthalpies, gas.X)
print(h_mole - h_check)
0

# At non-standard pressure, h_mole shows the correct pressure dependence, but the partial molar enthalpies do not:
gas.TP = None, 3*ct.one_atm
h_mole = gas.enthalpy_mole
h_check = np.dot(gas.partial_molar_enthalpies, gas.X)
print(h_mole, h_check)
0
```

**Checklist**

- [X] The pull request includes a clear description of this code change
- [X] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [X] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by decaluwe** [comment]
One question: I moved the "multiply by RT" step into the `for` loop.  Would it be faster, computationally, to keep this outside the loop, using `scale`?

**Comment by decaluwe** [comment]
FYI, I'm going to add a test to check that `h_mole = sum(h_k * X_k)`, as in the commit message.

**Comment by decaluwe** [comment]
Okay, once the tests finish running, this should be ready for review.

**Review by speth — APPROVED** [review]
Looks good to me.

As to the question about calling `scale` versus multiplying by `RT()` inside the loop, I think the latter (as you've opted for) is better, as it involves only one loop -- the `scale` function would have to loop internally anyway.

**Pull request merged**
