### PR TITLE
Add the Accelerate framework to the CMake builds of the samples

### PR DESCRIPTION
**Pull request by bryanwweber**
Adds the Accelerate framework to the CMake builds of the C++ samples on macOS.

Does the CI run the samples? If not, I can try to set that up.

### CODE REVIEW

**Comment by bryanwweber** [comment]
So I can't build the samples locally using CMake although everything works just fine with SCons. CMake complains that `fmt/format.h` can't be found. I can't see any difference between the explicitly included directories for the two methods. Any hints appreciated.

```
$ cd ~/cantera-test/.../rankine && mkdir build && cd build
$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine/build
$ make
/usr/local/Cellar/cmake/3.13.4/bin/cmake -S/Users/bryan/cantera-test/share/cantera/samples/cxx/rankine -B/Users/bryan/cantera-test/share/cantera/samples/cxx/rankine/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.13.4/bin/cmake -E cmake_progress_start /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine/build/CMakeFiles /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine/build/CMakeFiles/progress.marks
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/Makefile2 all
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/rankine.dir/build.make CMakeFiles/rankine.dir/depend
cd /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine/build && /usr/local/Cellar/cmake/3.13.4/bin/cmake -E cmake_depends "Unix Makefiles" /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine/build /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine/build /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine/build/CMakeFiles/rankine.dir/DependInfo.cmake --color=
Scanning dependencies of target rankine
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/rankine.dir/build.make CMakeFiles/rankine.dir/build
[ 50%] Building CXX object CMakeFiles/rankine.dir/rankine.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++   -I/Users/bryan/cantera-test/include -I/Users/bryan/miniconda3/envs/cantera-dev/include  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk   -std=gnu++11 -o CMakeFiles/rankine.dir/rankine.cpp.o -c /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine/rankine.cpp
In file included from /Users/bryan/cantera-test/share/cantera/samples/cxx/rankine/rankine.cpp:3:
In file included from /Users/bryan/cantera-test/include/cantera/PureFluid.h:9:
In file included from /Users/bryan/cantera-test/include/cantera/thermo/PureFluidPhase.h:17:
In file included from /Users/bryan/cantera-test/include/cantera/thermo/ThermoPhase.h:14:
In file included from /Users/bryan/cantera-test/include/cantera/thermo/Phase.h:12:
In file included from /Users/bryan/cantera-test/include/cantera/base/ctexceptions.h:14:
/Users/bryan/cantera-test/include/cantera/base/fmt.h:15:12: fatal error: 'fmt/format.h' file not found
  #include "fmt/format.h"
           ^~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/rankine.dir/rankine.cpp.o] Error 1
make[1]: *** [CMakeFiles/rankine.dir/all] Error 2
make: *** [all] Error 2
```
Here is `cantera.conf`:
```
prefix = '~/cantera-test'
python_package = 'minimal'
python_cmd = 'python3'
f90_interface = 'n'
system_sundials = 'n'
boost_inc_dir = '${CONDA_PREFIX}/include'
```

**Comment by speth** [comment]
The CI does not currently build or run the samples. You can do the former with `scons samples`, but that's not the same as actually using the generated `SConstruct` and `CMakeLists.txt`.

**Comment by bryanwweber** [comment]
OK, I fixed the build problems. I didn't realize that SCons had picked up the system version of fmt. I just pushed a change that should fix that CMake doesn't pick up `/usr/local/include` when `-isysroot` is set (which it is by default, at least on my computer).

I think this work came out of me trying to build the samples to test the install of the Conda package of libcantera. So now I need to go back to that and figure out where I was... 😄

**Comment by bryanwweber** [comment]
I also don't think its worthwhile to build the samples at this time. If we look at improving the CI system in the future, I think it can be something we integrate then.

**Review by speth — APPROVED** [review]

**Pull request merged**
