### PR TITLE
Created a sample ThermoPhase.pyx

### PR DESCRIPTION
**Pull request by Arsh0508**
**Checklist**

- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] The pull request is ready for review

**If applicable, fill in the issue number this pull request is fixing**

Fixes #

**Changes proposed in this pull request**

-
-
-

### CODE REVIEW

**Comment by Arsh0508** [comment]
@bryanwweber sir, I have wrote a demo wrapper for method/function "setState_PX" in class "ThermoPhase" in namespace "Cantera" supporting Pa and atm.
Please kindly review it once and if this is fine,  I will extend it to other methods, units and classes.

Regards,
Arsh

**Comment by bryanwweber** [comment]
@Arsh0508 I'm not sure this is a good approach. The problem is, what if a user wants to input pounds per square inch? Or pounds per square foot? Or kPa? Or... Hopefully you can see how treating each of these individually will be unsustainable. Moreover, this would have to be done for every method that requires units, which would be a lot of work.

Instead, I think a better approach will be to use something like Pint (as mentioned on Cantera/enhancements#3) and its `ureg.wraps()` method. In addition, I think it would be best to automatically generate the appropriate Python code that wraps each method in the .pyx files.

Hope it helps!

**Comment by Arsh0508** [comment]
@bryanwweber sir, though I haven't really worked with Pint in the past, but I sure will check that out right away and then write a demo cython code using the ureg.wraps() method, if you prefer it that way and get back to you.

Thanks for taking time off your schedule to review it!

**Comment by bryanwweber** [comment]
Superseded by #825

**Pull request closed without merging**
