### PR TITLE
Fixes to help with conda-forge builds

### PR DESCRIPTION
**Pull request by speth**
**Changes proposed in this pull request**

Fixes to resolve issues encountered while trying to update the conda-forge recipe (see conda-forge/cantera-feedstock#27), plus (unrelated) removal of a few unnecessary declarations.

- Relax tolerance on `test_phase_order_surf_jacobian`, which was failing by a slim margin on ppc64le Linux builds
- Fix OpenMP flags in generated `CMakeLists.txt` files -- see https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/VariablesListsStrings for some help understanding the rather non-intuitive CMake syntax.
- Implement workaround in sample SConstruct files for SCons ignoring `RPATH` on macOS
- Improve setting compiler in sample SConstruct files: do not set a default compiler for "package" builds, and allow the user to override using standard environment variables such as `CXX`
- Always allow the `conda` layout when using `package_build`
- Check return value of `soln_newSolution` in clib demo to avoid undefined behavior if the input file is not found
- Search the active conda environment for YAML files
- Fix cleanup of `-isysroot` flags in package builds
- Remove declaration for the method `MultiTransport::correctBinDiffCoeffs` which had no corresponding implementation
- Remove `friend` declarations from `DenseMatrix` -- these methods either don't exist with the specified signature (`invert`) or only access public members of the `DenseMatrix` class (`solve`) and don't need to be friends.

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by ischoegl** [comment]
There is another tolerance issue in #1271 (which was resolved by patching downstream) - I'd consider adopting this for the same rationale as provided here for `conda-forge`?

**Comment by speth** [comment]
I stand by [my comment](https://github.com/Cantera/cantera/pull/1271#issuecomment-1116350791) in that PR, and don't think the patch proposed there should be adopted as our baseline. It's not even clear at this point whether that patch is still necessary on those systems, or whether it was just a transient due to specific builds of g++ and/or glibc.

**Comment by ischoegl** [comment]
> I stand by [my comment](https://github.com/Cantera/cantera/pull/1271#issuecomment-1116350791) in that PR, and don't think the patch proposed there should be adopted as our baseline. It's not even clear at this point whether that patch is still necessary on those systems, or whether it was just a transient due to specific builds of g++ and/or glibc.

Sure. I was mainly asking as the tolerance adjustment was pretty minor, going from `rtol = 1e-14;` to `rtol = 1.2e-14;` - see [proposed change](https://github.com/Cantera/cantera/pull/1271/files). I'm fine either way, but I thought I'd bring it up. *PS: It is true that it is no longer clear whether this is needed any longer, and it probably shouldn't change under those circumstances.*

**Review by ischoegl — APPROVED** [review]
Thanks, @speth ... this looks all good to me!

**Pull request merged**
