### PR TITLE
Updates for 2.3.0 beta

### PR DESCRIPTION
**Pull request by speth**
This PR is for updates that should coincide with the start of the 2.3.0 beta period. Feel free to push additional updates to this branch, or let me know if there's anything missing.

### CODE REVIEW

**Comment by bryanwweber** [comment]
I pushed a fix for #335 in #400

**Comment by speth** [comment]
# Cantera 2.3 Changelog (full)

## Bugs Fixed

### Thermo / Species / Elements
- Fix incorrect index check in GeneralSpeciesThermo::reportParams (e21a7ce, #328)
- Fix pointer logic errors in initThermoXML in DebyeHuckel and HMWSoln (546eede)
- Fix IdealGasPhase constructor from XML_Node (ff60328)
- Synchronize Mixture/Multiphase state before printing report (ac9dfa0)
- Make continuity check for enthalpy dimensionally consistent (1c09f7f)
- Fix silent failures in HP/UV/SV/SP convergence (5b1a4a6, #264)
- Fix pure fluid thermal expansion coefficient calculation (b1a1ce6)
- Fix calculation of derivative properties of pure fluids near or inside two-phase region (a92245f, #273, 3f3b965)
- Check for null species thermo when adding species (b7fad42)
- Correct calculation of activity concentrations in `RedlichKwongMFTP` (d655cf0)

### Kinetics
- Fix handling of integral, explicit reaction orders (4efad93)
- Fix indexing error in ImplicitSurfChem::eval (2dfa43f)
- Always initialize FalloffReaction.falloff (60efb22, #326)
- Fix reported values of degenerate falloff parameters (84e6775, #404)

### Transport
- Fix segfault when species transport data is missing (bab0786, #312)
- Use correct scaling factor when fitting conductivity (b7e1a5f, #345)
- Fix species geometry check for charged species (2284bc9)

### Reactor networks
- Fix segfaults in updateMassFlowRate due to unset parameters (c0fa589, #278)
- Check for Reactor contents before installing FlowDevice (f6f868f, #279)

### 1D flames
- Fix transient mask after Jacobian update to improve timestepping convergence (d767049)
- Always switch to "steady mode" before attempting steady-state solve (9353a79)

### Python package
- Fix full-state (e.g. TPX) properties of PureFluid (48c6c6b, #307, #308)
- Fix exception handling when setting soret_enabled (e100ef9)
- Fix error in setting 1D tolerances for specific components (c799edf)
- Fix range of components used when settings 1D solver species tolerances (809223f)
- Fix errors when long strings are passed as `source` arguments to `Solution` (3593fad, #416, d9ff992)

### Matlab toolbox
- Fix 'nAtoms' to work with species with negative atoms (0e4b0cb)
- Fix setState_sat*.m functions (5aabfe9, #299, #300)
- Fix printing of error messages (8b64b6f)
- Fix default threshold value when displaying phase info (69f25b4)
- Fix ThermoPhase 'clear' method (c16c153)
- Always allocate string buffers of an appropriate size (940b7ea, #118)

### Examples / Samples
- Fix compilation errors and warnings in the C++ examples (571eaed)
- Fix syntax error in extract_submechanism.py example (eb2df78)
- Fix Python multiprocessing example (7ca9327, 6514f7a)
- Save correct system state after integration step (8ffbbea)
- Link Fortran sample programs to the correct standard library (3261b41)
- Fix Makefiles generated for C++ examples (bc609ce)

### Other
- Fix conversion of Chemkin files where NASA polynomial is only given for a single temperature range (2f7e050, 233399f)
- Fix invalid iterator usage in Application::close_XML_File (8dcde36)
- Fix definition of elemental mole fraction (e8292d3, #286)
- Fix a compilation error when using '-std=c++11' (567a854)
- Fix compilation using Visual Studio 2015 (5ed6d9a)
- Fix possible memory leak in newPhase (c2ba24c)
- Fix errors in DenseMatrix for rectangular matrices (b94e272, bd24aeb, 7af1b4b, c0c9a4e)
- Fix memory leak in CVodesIntegrator (cd77a94)
- Fix vec2str to actually use provided format string (e13faa1)
- Fix BandMatrix assignment operator (af3de9a)
- Fix ElemRearrange when unused elements are present (0bd8892, #361)
- Fix for multiple definitions of '_xml' function (f0e6d09)

## Changes to existing capabilities

### Thermo / Species / Elements
- Check for non-existent species in setMass/MoleFractionsByName (140da43)
- Check for NaN when setting state (bb2d1c0, 6e138d0)
- Show large negative species concentrations in phase report (86835a5)
- Treat duplicate keys in composition strings as errors (b38a933)
- Merge classes StoichSubstance and StoichSubstanceSSTP (0542e69)
- Add compatibility check for phases added to MultiPhase (a026c6a, #306)
- Check dynamic_cast to PDSS_Water (aa5f26b, #6)

### Kinetics
- Prevent positive feedback in negative species concentrations (60b98b3)

### Transport

### Reactor networks
- Eliminated confusing argument to ReactorNet.step() function (8d4e9bf, #271)
- Deprecate possibly-ambiguous names in componentIndex (0590b2c, #274)
- Add bounds check on sensitivity parameter index (d44f46a)
- Prevent adding sensitivity reactions to initialized ReactorNet (d8772f2)
- Add ReactorSurface to simplify use of surface reactions (3f76637, c3b9a0c, a7aec57)
- Handle zero-size timestep in CVodesIntegrator::advance (64bb049)
- Use setCoveragesNoNorm when evaluating ReactorSurface (7f121a9)
- Add methods Reactor::setChemistry and chemistryEnabled (c344b4c, 108b423, 0e835e4, 8ada40f, #359)
- Suppress recoverable errors in RHS function by default (ecb2868)

### 1D flames
- Improve fixed temperature selection for FreeFlame (7484827, 22537b9)
- Use better default initial grids (de8348e, f0a1e25, 87a8419, 8e81292, 77e3775)
- Use better initial guess for FreeFlame mass flow rate (a9293c3, 5a08cf0, 85c3bf5)
- Only reset Jacobian age after successful *steady-state* solve (39a6819)
- Improve finite-difference Jacobian by preserving sign of perturbed components (011c9cb)
- Tighten default negative species bounds (5a576a7)
- Improve handling of negative species concentrations (318fa04, 2d82c78, b99ba44)
- Set limit on number of timesteps without reaching steady state (29b7049, 4c5301d)
- Increase default value for maximum timestep (7ba6681)
- Improve Jacobian evaluation for ReactingSurf1D (af5bbf7)
- Use most prevalent species to impose sum-of-mass-fractions constraint (9f3821d)
- Use better guess for CounterflowDiffusionFlame initial position (6c466f6)
- Use new default values for Jacobian and time stepping settings (059e657, b56094b)
- Make Jacobian atol independent of compiler optimizations (a288d5c)
- Sim1D::setProfile checks range of position array (f4ad150)
- Make exceeding the max number of grid points an error (0a363a1, c91bdee)
- Change the default max number of grid points to 1000 from 3000 (0b9a741)
- Remove default arguments from setMaxGridPoints (44b2186)

### Python package
- Regularly flush stdout when printing from C++ (0703770)
- Print values which cause exceptions in the error message (4379a07)
- Add messages to assert statements in thermo property setters (4829310, #335, #400)

### Matlab toolbox
- Move lowercase air.m to uppercase Air.m to be consistent with the other PureFluid functions (cf49649)
- Deprecate `importPhase` function in favor of constructor for class `Solution` (5b24064, 1e08d74)

### Other
- Remove unimplemented option to use QR factorization in BandMatrix (c08c365)
- Simplify error handling to eliminate need for global error stack (ee95c60)
- Fix get_modified_time to avoid race condition on Windows (05198dd)
- Show messages from std::exception in CVODES residual function (e454c51)
- Improve error message generated by XML parser (26b9376, ca2a330, #40)
- Check index bounds for known problems in VCS_SOLVE (2561ab8)
- Move CANTERA_DATA environment variable up in search path (dac5345)
- Add notices to documentation for classes with no tests or examples (5af1dfd)
- Add buffer length argument to all clib functions returning strings (8a9eabe)
- Remove trailing commas when printing Array2D and BandMatrix (43f7bc8)
- Failures in BandMatrix raise exceptions; eliminate bandmatrix.csv (b9ac39b)
- Deprecate various unused functions and classes and arguments (many; see http://cantera.github.io/dev-docs/doxygen/html/deprecated.html for details)
- Many Documentation updates

## New Features

### Thermo / Species / Elements
- Added RedlichKwongMFTP::cv_mole (7426fca)
- Add functions for setting density and pressure simultaneously (#272, 5d215b7, 8e58a45, 2045505, 6082726, ce21b08)
- Add new interface for accessing element information (f3bc7a5, c324386, ba8c906, b351c62, 9577409, 9276f56, f95f118, c72f1b6, efd6d23)
- Add functions to set additional property pairs for pure substances (63cfed1, 49cb039, 71e2101, c1f287d, bff8d10, 02f0e27, #315)
- Add RedlichKisterVPSSTP::s_update_dlnActCoeff_dlnX_diag() and tests (125d2e0, #293, 1183479)
- Add ability to modify species data for existing Phase objects (4428a62)
- Allow non-positive atomic weights for custom elements (abf71c4)
- Make species names case-preserving instead of case-sensitive (f17750e)
- Allow colons in species names (3300611, 1db103c, 8e6d53d, 0787e41, #343, #396)
- Allow discontinuous thermo warnings to be suppressed (aa4d07f, #354)

### Kinetics
- Added methods to InterfaceKinetics to get effective rate parameters (40e0904, #297)
- Allow adding species after reactions for homogeneous kinetics (1ba5f6b)
- Add option for Motz & Wise correction to sticking reactions (1e5eb8c, 593ab8a, fd9d60f, e851e5e)

### Transport
- Automatically reinitialize after change in number of species (178b452, 46b97be)

### Reactor networks
- Implement functions getState for reactors and reactor networks (16ab7df)
- Implement the Cython function advance_to_steady_state (57e3ee8, #95, #303, 304364c, de133f1)
- Implement enthalpy of formation sensitivity analysis (cf13b31, 3a12967)
- Add componentName function to ReactorNet and Reactor classes (8ff82c0)
- Add flow-device-specific methods for setting coefficients (c64b714)
- Allow Reactor to be used with PureFluidPhase objects (1dc0ced, #257, 28202f9, 95764fd)

### 1D flames
- Generalize initial profile generation for diffusion flames (51e0c91)
- add function for getting info about a solution component (d20ab89)
- Add ability to access last successful timestepped solution (832ee88)
- Keep track of number of time steps taken before each steady-state solve (11b665b)
- Add accessors for solver statistics (532e132)
- Add function for restoring last successful steady-state solution (81074b2, 1f3e8dd)
- Add accessor functions for steady and relative tolerances (f13e271, 7d14677)
- Introduce 'auto' option to Sim1D.solve (d2793c0, 77c7442, 92ccda8, 3b522dc, 3fd46f7, 170f1d0)
- Allow replacing flow domain grid after creating Sim1D (5e35ca5)
- Add a Twin Premixed Counterflow Flame class and example (f699748, #340, ed72984, 828cca3, 1dc7071, 036eeb1, #356)
- Add callback hooks to make debugging 1D solver easier (efe43b3)
- Add maxPoints and maxGridPoints functions (6acf755, a82dd5a, 06a739d, #387)
- Add general support for calculating adjoint sensitivities (ca8b101, 0bfdf14, 4753ae4)

### Input file handling (ck2cti, cti, ctml_writer)
- Print the current thermo entry when an error is encountered (b25167e, bd53bbd)
- Handle reactions containing 'hv' pseudospecies (5926d2d)
- Add 'nonreactant_orders' option to allow non-reactant orders (7e71645, #317, #321, a68cdec, 828fba5)
- Add support for Chemkin-style extended elemental composition (9e5362a)
- Allow elements/isotopes with custom atomic weights (7d18120, #344, #314)
- Support conversion of surface mechanism files (#76, db90a7c, de9bb5b, cff277d, aa42aa5)
- Support different units in different REACTIONS sections (ff3429f)
- Provide better error message for reactions with missing data (fe747f3)
- Don't include reactions with explicit reverse rate equal to zero (a9814a1, 05ad05c, #380, #398)
- Provide better error message for species with invalid transport data (0657861, 3f382e2)

### Python package
- Make thermo parameters accessible in Python (cd545af #275, #276, #277)
- Add class Quantity (#290, 94f94dd, d559af9, 0325377, 8299646, 25b1dc9, a77b79b)
- Add support for Numpy 1.10 (512dffe)
- Add wrapper for SurfPhase::setCoveragesNoNorm (011a64a)
- Add Reaction.__contains__ method (2bfbd73)
- Add ThermoPhase.set_equivalence_ratio (9c907af)
- Add class SolutionArray (#329, 78d275b, 21a1be8, b51b844, 5c23ea3, 366ff04, 2d32a35, 00b104a, deafbf8, 69bec84, beb2056, 59e0f5a, f2ac1f2, 001b7e9, faa4c36, 00d254a)
- Allow adding species / reactions from Python (1660167, e49f843)
- Add CanteraError class for execptions (89d0c56, 4e1c45c, 9c368d5, #370)

### Matlab toolbox
- Extend NoNorm option for setCoverages to the Matlab toolbox (14864e8, #305)
- Add missing PureFluid constructors for fluids defined in liquidvapor.xml (ee9d575)
- Add function for getting Cantera version (5641fa8)

### Examples / Samples
- Add C++ example showing initializaton of Kinetics and Transport (a2aade2)
- Generate CMakeLists.txt files for C++ and F90 samples (f959fa6)

### Other
- Introduced Continuous Integration testing using Travis CI,  AppVeyor, and codecov.io (aa7f5a2, 67e6d6c, 13c8ba6, 2b2f733, dd7a374, c0d007a, c770edf, 361ca83, 1e87756, 29e935c, ca6f8f4, 9f198f0, 733ec18)
- Make clib usable as a pure C (not C++) interface and add tests (e332fcb, deee889, 100d6db, 5f0e20b, deeb619, 902ab5c)
- Add support for Sundials 2.7 (ad7a02d, #366)
- Add function to get the data directories Cantera searches (d1c2ec4, 1cdc6b6, #375)
- Add contributing guidelines and templates for Github Issues/Pull Requests (557e752, 8ef3316, 0c400a9, d55ffa9, #395)
- Add Code of Conduct (3782543, #392, #393)
- Added Conda build recipe and made binaries available through anaconda.org (#261)


## Other code improvements

### Thermo / Species / Elements
- Convert Shomate coefficients when creating objects (b7a5aff)
- Consistently use ThermoPhase::RT() (ceefc5e, 5e69a99)
- Simplify ThermoPhase constructors (7fe8f0f, 7bcbbaa)
- Simplify adding species for most phase types (9c4a0ba)
- Introduce Phase::compositionChanged (32b3543)
- Add function 'resetHf298' (0e2ea09)
- Consolidate duplicate species checks in Phase::addSpecies (11f6c2f)
- Make tolerances used in state setters more consistent (478a62d)

### Kinetics
- Eliminate unnecessary variables available through Reaction (f623e44, 62f2af5, 4f1250e)
- Eliminate need for 'finalize' method (1f231d1)

### Equilibrium solvers
- Standardize VCS solver to always use MKS units (511a39f)
- Fix formatting of some VCS debug output (d1a58e1)

### Reactor networks
- Move sensitivity parameter vector into FuncEval (032bb9c)
- Eliminate re-ordering of sensitivity parameters (c7a1a57)

### 1D flames
- Use c_offset_Y instead of literal value "4" (6d5e28e, #371, #372)
- Eliminate unnecessary state variables from boundary objects (52727a9, 0740131, b01f9cd)

### Input file handling (ck2cti, cti, ctml_writer)

### Python package
- Move composite classes out of Cython (8a86fed)

### Matlab toolbox
- Switch PureFluids to use liquidvapor xml file (9977fd6)

### Examples / Samples
- Update C++ flamespeed to use current best-practices (b50ef03)
- SConstruct for C++ demos inherits compiler and options (0a3927a)
- Install data file for LiC6 electrode example (ec38f58)
- Generate SConstruct and Makefile for LiC6 electrode example (8b62a59)

### Test suite
- Update some legacy tests to utilize the GTest framework (e34b273, c234437, 30d1d5e, f252ff1, 1cc0d42, 61a4571, a75a8f2)
- Fix issues running test suite in parallel (c446686, 1d7104a)
- Fix error in test comparison when numbers disappear (d69daab)
- Handle Warnings in Python test suite (92d3ba0, 5811035, 3914ede)
- Fix LD_LIBRARY_PATH order when running tests (a7db9a7, #310)
- Add tests for class BandMatrix (9a8d244)
- Add more tests of flame solver convergence (1730036, 522d263, 3e371c8, dfb4d62, 2315da5)
- Add test of VCS equilibrium solver with higher loglevel (1a64a23)
- Update tests to sometimes use VCS 'estimate_equil' option (7082455)
- Make deprecation warnings fatal in test suites (7124385)
- Show largest error component in assertArrayNear (92e9e08)
- Fix failures involving use of global variables in tests (62524e8, #351)
- Fix spurious test failures caused by assertAlmostEqual (5ec525d)
- Relax tolerance on Polyfit.exact_fit test (791c9d1)
- Make reaction rate comparisons in tests more granular (50d0f99)
- Make Python test suite runnable from an installed copy of the Python module (ea4b350, fc92707, e235f69, #376, #381)

### Build system improvements
- Fix issues with Cantera.mak (eb75e8b, 812cbc4, b395c68)
- Fix Python module when using Cygwin (2b7bcf2)
- Switch Cython and python interfaces to use setuptools, and provide executable scripts for ck2cti & mixmaster (#283, #288, b979cea, 5f8bd40, 19f4468)
- Improve uninstallation of the Python module (2334410, #287)
- Optionally show contents of config.log after errors (c88aaf9)
- Fix incorrect directory created in build tree (84566a3, #304)
- Miscellaneous build system improvements (c983d73, 592a40a)
- Fix installation location for Python module location on OS X (03db1d3, #296)
- Use submodule for Sundials if system Sundials is not installed (34e38ab, b4a1fb2, 4e551f6, #309)
- Allow compiler options which contain commas (2e56f6d, #320)
- Fix Cantera.mak when blas_lapack_dir is empty (31c6637)
- Fix setting of prefix when building Debian packages (6d91b44)
- Fix fallback behavior with explicitly-specifed Fortran compiler (60eed78)
- Install license file with licenses for 3rd-party code (e71f22a, c557fa8)
- Link statically to libstdc++ on Linux to avoid conflicts (e2d7e17)
- Check for numpy before deciding to build the Python3 module (bdb088d)
- Validate values of target_arch (8ef4f64)
- Make check for Fortran compiler more robust (91161f0)
- Fix paths, modify library linkage, and generate versioned shared library to enable Fedora packaging (9b318f3, #318, 908e620, feca44a, d7819af, #346)
- Fix default Python module installation path on Debian/Ubuntu (e70e5bf)
- Rename minimal Python interface package to be PEP 503 compliant (fea1a36)
- Fix Fortran compiler used when determining configuration (5435af2, #360)
- Use precompiled header to speed up compilation (cbcce07, e3dfc35, 2a8ac43, 334b154, 1453358, 32ab413, 9c44db3)
- Fix permissions error when installing to stage directory (baa0a24)
- Use python3_array_home option (adcd5de, #388)
- Check for NumPy using python_cmd if specified (7d3ebdd)
- Fail check for Numpy gracefully (3014b7a, #414)

### Other
- Remove execute bit from files that don't need it (0b5a46f)
- Use git submodule for googletest (4a411b7)
- Make pointer member variables regular members where possible (ffc4ba0, 0690626)
- Remove uneeded .close() calls (b751087, #298, 7562d79)
- Add invalidateCache() function to ThermoPhase and Kinetics (13fa0c7, 51b0e46)
- Add version of XML_Node::build that takes file name directly (6003af0)
- Use Sundials and Eigen to eliminate the need for bundled LAPACK (41ae065, 41a357a, bf67cce, b49c2e4, a7d854f, 799695f, 230688d, efb068e, df43a47, c677d13, #333)
- Introduce basic registration capabilities for factories (f985169)
- Replace arbitrary numerical constants with strings (0f71bbc, 7f21aa0, bd8a5d0, 6b588c5)
- Remove dummy element from elements.xml (6138a39, #363)
- Fix some const-correctness issues (e83b095, 8398982, 40630a3, b51c1b8, #368)
- Eliminate debug_verbose option and DEBUG_MODE macro (e58bd09)
- Replace overly-specific exception types with CanteraError (b55c8fe)
- Use Boost implementations of various functions instead of relying on home-grown alternatives (367bdba, b25784d, 7a24dc3, da87260)
- Use fmt (cppformat) for string formatting operations (many commits)
- Compile as C++11 code and utilize C++11 features (many commits)
- General cleanup of C++ source code formatting and style (many commits)
- Refactoring of C++ source code to reduce redundancy (many commits)
- General cleanup of Python source code formatting and style (many commits)
- Remove unused variables and unimplemented/unnecessary functions (many commits)
- Fix various compiler warnings (ee1b07a, 7ee4758, 4582e72, 6690b96, a01032c)
- Remove unnecessary files from source distribution (many commits)

**Comment by speth** [comment]
I tried to make an abbreviated version, and even this ended up being long. Maybe we need to make releases more frequently. Feel free to edit this to make it shorter.

*I'm just going to use this comment to draft the announcement for 2.3.0, since it lets me keep all the nice automagic links to Github issues and commits if I do it this way.*

-----
Dear all,

I am pleased to announce the release of Cantera 2.3.0. There have been many changes and improvements since Cantera 2.2.0 was released in June 2015. A somewhat abbreviated Changelog is included below, in addition to note on installing Cantera 2.3.0 using a variety of methods.

Regards,
Ray

## Installing Cantera 2.3.0

Cantera 2.3.0 introduces a new installation option for the Python package, which is the `conda` package manager for the Anaconda / Miniconda Python distributions. If you already have an existing conda environment, you can install Cantera 2.3.0 by running
```
conda install -c cantera cantera
```
For more details on installing conda and using Cantera with conda, see http://cantera.github.io/docs/sphinx/html/install.html#conda.

The source code and Windows binaries can be downloaded from Github: https://github.com/Cantera/cantera/releases. To use the Matlab toolbox on Windows, install both `Cantera-2.3.0-x64.msi` and one of the Python modules. The Python installers are standalone and do not require the base Cantera package. Installers are available Python 2.7, Python 3.4, Python 3.5, and Python 3.6. Additional installation instructions for Windows can be found at: http://cantera.github.io/docs/sphinx/html/install.html#windows.

For Ubuntu users, Cantera 2.3.0 packages for both 16.04 (Xenial Xerus) and 16.10 (Yakkety Yak) are available via the PPA at https://launchpad.net/~speth/+archive/ubuntu/cantera. See http://cantera.github.io/docs/sphinx/html/install.html#ubuntu for additional details.

For macOS users, Cantera 2.3.0 will be available pending resolution of Homebrew/homebrew-science#4860. See http://cantera.github.io/docs/sphinx/html/install.html#homebrew for additonal instructions.

And of course, you can also just check out the source code directly using Git from https://github.com/Cantera/cantera. Compilation instructions for all platforms are located at: http://cantera.github.io/docs/sphinx/html/compiling.html.

## Documentation
Documentation for Cantera 2.3 can be found at: http://cantera.github.io/docs/sphinx/html/index.html.

## Issues & Feedback
Please report any issues on the Github issue tracker at https://github.com/Cantera/cantera/issues. When making a bug report, please specify the exact version of Cantera you are using (i.e.
list the last git commit hash if you are using a git checkout) in addition to providing information about the operating system, compiler versions, Python version, etc. that you are using.

There are number of rarely used or redundant features which have been slated for deprecation. Using these methods in Cantera 2.3 will show a deprecation warning, and these methods will be removed before the following release of Cantera. You can examine the list of deprecated functions at: http://cantera.github.io/docs/doxygen/html/deprecated.html. If you believe any of these deprecations are unwarranted, please create an issue on Github.

In addition, there are a number of classes and features that have been identified as being potentially unused. They are not used internally within Cantera, have no test coverage, and have no examples available. These classes are identified in Issue #267. If you utilize any of these classes, please consider providing tests or examples which can be integrated into Cantera. If these classes and features remain in their current state, they are likely to be deprecated and removed in a future release.

## Changes in Cantera 2.3.0
Highlights are listed here. See the [full changelog](https://github.com/Cantera/cantera/pull/399#issuecomment-263736973) for more.

- Add ability to modify species data for existing Phase objects
- Make species names case-preserving instead of case-sensitive, and allow colons in species names
- Add option for Motz & Wise correction to sticking reactions
- Implement enthalpy of formation sensitivity analysis for reactor networks
- Implement the Cython function `advance_to_steady_state` for reactor networks
- Eliminate most known 1D flame solver failures by improving Jacobian evaluation, and using better default initial grids and initial guesses
- Introduce 'auto' option to Sim1D.solve to automatically try multiple initial grids
- Generalize initial profile generation for diffusion flames for arbitrary fuel/oxidizer combinations
- Add general support for calculating adjoint sensitivities for 1D flames
- Add a Twin Premixed Counterflow Flame class and example
- Support conversion of surface mechanism files
- Provide better error message for problematic reaction and thermo entries when converting input files
- Add 'nonreactant_orders' option to allow non-reactant orders
- Allow adding species / reactions from Python
- Add new classes `Quantity` and `SolutionArray` to Python
- Make Python test suite runnable from an installed copy of the Python module
- Introduced Continuous Integration testing using Travis CI and AppVeyor
- Use Git submodules for Sundials, Eigen, Google Test, and libfmt if system versions are not installed
- Use Sundials and Eigen to eliminate the need for bundled LAPACK
- Added Conda build recipe and made binaries available through anaconda.org
- Add support for Sundials 2.7
- Deprecate unused classes, functions, arguments, and constants (see http://cantera.github.io/dev-docs/doxygen/html/deprecated.html for details)
- Add notices to documentation for classes with no tests or examples (see https://github.com/Cantera/cantera/issues/267)
- Make clib usable as a pure C (not C++) interface and add tests

**Comment by speth** [comment]
First-cut Windows binaries are at: http://gir.mit.edu:8010/nightlies/. I've only had a chance to test a couple of them, but I think they're good enough to make the beta announcement.

@bryanwweber Unless you have any further comments, I'm ready to merge this and then we can trigger the conda builds.

**Comment by bryanwweber** [comment]
I'm 👍  on the merge and release. I'd suggest we do more frequent bugfix patch releases so the Changelog doesn't get quite so long between releases.

Once you merge, I'll take a look at what we should do for the conda recipes. I think we need a new recipe/branch for 2.3.0 that uploads to the main label (but that should wait for the final release).

**Comment by speth** [comment]
Right, I think the conda builds for the beta should still be on the master branch and use the `dev` label, and we should create a branch for the stable builds when 2.3.0 final is ready, such that the branch structure for the conda recipes matches the structure of the main cantera repo.

Should we reset the `build number` on the conda build since the version has gone from 2.3.0a3 to 2.3.0b1?

**Comment by bryanwweber** [comment]
OK creating the branch structure should work because the CI builds on all the branches, not just master. For that, I think it would be better to have the source tarball downloaded from the official release page, so the conda package always matches an actual release, and not a random commit on the 2.3.0 branch. 

I think we should check that `2.3.0b1` is read as a newer version than `2.3.0a3`, and if it is, reset the build number. Alternatively, we can delete the existing files from anaconda.org and reset the build number.

**Comment by speth** [comment]
Yes, it should download either the tarball or specify the commit that's
tagged as the 2.3.0 release.

2.3.0b1 had better be read as newer than 2.3.0a3. In any case, it's
probably worth cleaning out all of the random alpha builds once we add the
beta.

**Pull request merged**
