### PR TITLE
Fix Ubuntu packaging issues

### LINKED ISSUE #1393: f77-demo test fails for OpenBLAS / MKL
**Problem description**

The `f77-demo` test fails for optimized LAPACK libraries. See referenced GH runner output below (which uses Intel MKL for the OneAPI toolset). Similar behavior can be observed for OpenBLAS.

**Steps to reproduce**

1. Enable optimized LAPACK libraries (Intel MKL or OpenBLAS).
2. Run `scons test-f77-demo`

**Behavior**

See OneAPI runner - [GH Actions output](https://github.com/Cantera/cantera/actions/runs/3033761690/jobs/4882196311)

**System information**

- Cantera version: latest `main`
- OS: all(?)
- Python/MATLAB/other software versions: N/A

### PR DESCRIPTION
**Pull request by speth**
**Changes proposed in this pull request**

This fixes some issues that affected packaging for Ubuntu, or were otherwise identified while bringing the scripts for building those packages up-to-date for the changes in Cantera 3.0.

- Remove special handling for Debian filesystem layout from SCons, and leave this to the distribution-specific scripts
- Update minimum Cython version -- compatibility with Cython 3.0 and the use of the `noexcept` keyword requires 0.29.31 or newer.
- Relax tolerances for f77-demo test. This fixes #1393
- Fix files incorrectly marked as "executable"
- Fix a typo that broke the warning for insufficient Cython versions
- Avoid linking unnecessary libraries when linking to the Cantera shared library
- Remove Makefile generation for samples and `Cantera.mak`
- Cleanup includes/libs in generated build scripts
- Fix missing RPATH specification in generated SConstruct files for Fortran samples

**If applicable, fill in the issue number this pull request is fixing**

Closes #1393

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Review by ischoegl — COMMENTED** [review]
Thanks, @speth ... looked over the changes, and things look ok to me. Given the maintenance overhead, removing Debian-specific layouts and Makefiles are :+1: from my perspective.

**Review by ischoegl — APPROVED** [review]

**Comment by ischoegl** [comment]
Regarding the failing Python samples, I have a fix in #1507/#1508 - 2b8f5ed24247b67be48df15661469d23fc033a62 - feel free to cherry-pick.

**Comment by ischoegl** [comment]
@speth ... I believe this can be merged as the failing tests are fixed by #1507?

**Comment by speth** [comment]
Yes, agreed. I wasn't worried about those test failures, as they are clearly unrelated to the contents of this PR, and you've already fixed them elsewhere.

**Pull request merged**
