### PR TITLE
Const density stand conc

### PR DESCRIPTION
**Pull request by decaluwe**
Fixes # 458.

Changes proposed in this pull request:
-`ConstDensityThermo:standardConcentration(k)` returns `density()/molecularWeight(k)`, rather than the previously incorrect `molarDensity()`
-
-

### CODE REVIEW

**Comment by decaluwe** [comment]
Okay, so it looks like this is failing b/c of sofc_test, which is probably compared against calculations using the faulty standardConcentration outputs.  I'll need to re-run those manually and figure out if 
a) that is truly what is going on, and
b) what the 'assert near' value *ought* to be.

**Comment by speth** [comment]
Steven, I think your assessment of the problem is correct. I would note that `sofc_test` seems to be the only place within the entire test suite that ever makes use of this phase model, so there may be other issues lurking within this model as well.

**Comment by decaluwe** [comment]
Good thing I never used it for anything important… just my dissertation.  ;)

**Comment by decaluwe** [comment]
Okay, @pweddle and I have done a little more work (him) and thinking (me) on this.  There are a bunch of issues that need to be resolved, beyond what is above.  Wanted to run it by you all:

1. It is weird to me that specifying `incompressible_solid` in the cti file creates a `constDensityThermo` object.  I would think an incompressible phase is one with constant molar density, not constant mass density.  I don't know that such a model exists, so correcting this assignment would be longer term.  

2. If we do create such a model and re-assign the `incompressible_solid` label to it, I suppose one might also want to create a label on the cti level that *should* create a `constDensityThermo` object.  To be honest, I don't know that this is a really useful model - the only time I would think of a solid as having constant mass density is if the composition doesn't change - but this is already covered by the `stoichiometric_solid` model.  But at this point removing options from users seems like an odd move.

3. Regardless of the longer-term solution, a constant-density model is a terrible idea for any solid phase with a zero-mass vacancy species.  Correcting the `constDensityThermo::standardConcentration` routine so that it returns `density()/molecularWeight(k)` brings this to a head.  I think we ought to put an error or warning in this class, which screens for zero-mass species and warns the user.

4.  In terms of the `sofc_test.py` that is failing, I think `LatticeSolidPhase` would be a more appropriate model for the `oxide_bulk` phase.  @pweddle is currently looking into that, to evaluate if it is in fact the appropriate model and if there are any other unintended consequences to making that switch.

**Comment by speth** [comment]
Steven, I think the `IdealSolidSolnPhase` class provides a model where the molar density of each species is constant, which I agree is more useful (and physically meaningful) than one which holds the total mass density constant. Less clear to me is whether `IdealSolnGasVPSS` also does something similar.

If the `constDensityThermo` class is actually not useful (or worse), then we should deprecate it and plan on removing it.

At some point, I would like to have better correspondence between the C++ class names and the model names used in the input files. This certainly seems to be one of the cases where those names are furthest apart, and it ends up misleading users. Probably makes sense to work on this in conjunction with the new input format.

Having looked at the `LatticeSolidPhase` recently, it certainly looks like it is meant to handle things like vacancy species. It might be worth seeing if `IdealSolidSolnPhase` handles this just as well, without the additional layer of complexity that the `LatticeSolidPhase` introduces by having a phase containing more phases.

**Comment by decaluwe** [comment]
Hi Ray,

1.  Yes, I think constDensityThermo should be deprecated.  I just spent the morning trying to find ways to get this phase workable, in terms of the standard concentrations, and just kept running head-first into the illogical nature of the underlying assumption of the model.

2.  Agreed that LatticeSolidPhase appears to be more complex than most users will have a need for.  Even loading just a “Lattice” phase ran into some problems, when it came to kinetics.  My preference at the moment is to get IdealSolidSolnPhase working.  I’d like to get it working at the cti level, so that we are not really removing functionality in terms of the sofc_example.py that initially triggered this investigation.  @pweddle is currently working on this.

Thanks,
Steven

**Pull request closed without merging**
