### PR TITLE
Miscellaneous build system improvements, and mark release of Cantera 2.5.0

### LINKED ISSUE #969: Error starting the program
Hello! 
I am trying to run "A Very Simple C++ Program" and I have a problem:

***********************************************************************
CanteraError thrown by ct2ctml_string:
Error converting input file "/usr/local/share/cantera/data/h2o2.cti" to CTML.
Python command was: 'python'
The exit code was: 1
-------------- start of converter log --------------
sys.path: ['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
ImportError: No module named cantera
--------------- end of converter log ---------------
***********************************************************************
I have successfully compiled the source code on the ubuntu 20.04 operating system and successfully installed cantera.

The following programs are installed on my computer:
Python 2.7.18
Python 3.8.5
GNU (gcc v.9.3.0)
pip 20.0.2 (for Python 3)
Boost
SUNDIALS

I also installed other programs for the successful compilation and installation of cantera.

I am confused by the type of error and I do not know how to fix it

Please help me! Thank you in advance!

### PR DESCRIPTION
**Pull request by speth**
Most of these changes address issues I ran into while trying to build the Ubuntu package. A couple are related to issues identified while investigating #969.

**Changes proposed in this pull request**

- Update shebang lines in Python scripts to specify `python3`
- Add man pages for the CTML converter scripts
- Make SRI test data file non-executable
- Remove warning about untested Sundials versions for versions up to 5.7 (which is the current release)
- Print the installation location of the minimal Python module
- Update the logic for installing the minimal Python module to match what we do for the full module
- Don't invite the use of `sudo` when running `scons install` (per discussion on #963)

**If applicable, fill in the issue number this pull request is fixing**

Fixes #969

**Checklist**

- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] The pull request is ready for review

### CODE REVIEW

**Review by bryanwweber — CHANGES_REQUESTED** [review]
Thanks @speth! I have a few questions/comments:

1. I don't understand the commit message on e590fb6b80aace31aeb4408df9ae2e84f9e91d2a. I don't see how that change will affect only the minimal interface. Can you clarify the commit message?
2. I checked the conversion scripts to make sure any changes since `a3` would not change the output. I found that `air.cti` had a little bit of reduced precision compared to `gri30_tran.dat`, meaning that there's an extra digit of precision in the new `air.yaml` compared to `air.cti`. I doubt this will affect anyone's results too much, but we probably want to note it in the release notes somewhere.
3. The `ohmech.cti` file has the phase `ohmech-multi`, which should be added to `ohmech.yaml` and deprecated, like we did for `gri30.yaml`.

Otherwise, I think these changes look good!

**Comment by speth** [comment]
e590fb6 only affects the minimal Python module because it's editing `interfaces/python_minimal/SConscript`, not `interfaces/cython/SConscript`.

**Comment by bryanwweber** [comment]
> [e590fb6](https://github.com/Cantera/cantera/commit/e590fb6b80aace31aeb4408df9ae2e84f9e91d2a) only affects the minimal Python module because it's editing `interfaces/python_minimal/SConscript`, not `interfaces/cython/SConscript`.

🤦‍♂️ Dangit! Thank you for pointing that out.

**Comment by speth** [comment]
Regarding (2), the issue with transport coefficient precision dates from the old C++ version of `ck2cti`. I fixed the values in `gri30*.cti` in 8bcb62f727, which is part of this release, but had not noticed that it affected any other CTI files. I guess we will have the corrected coefficients for any YAML input files that were created using `ck2yaml` rather than `cti2yaml`. And agreed that this should be noted in the changelog, as the change for `gri30.cti` did slightly change a bunch of test results.

**Comment by speth** [comment]
@bryanwweber, I added commit fb9829850 which I think takes care of (3).

**Review by bryanwweber — APPROVED** [review]

**Comment by bryanwweber** [comment]
Woo! Feel free to merge + tag when the CI finishes.

**Pull request merged**
