### PR TITLE
Add macOS M1 runner

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

macOS Apple Silicon runners are now available in beta (see [standard-github-hosted-runners-for-public-repositories](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)). This PR is a simple test whether things work at the moment.

- 🚧 
-
-

**If applicable, fill in the issue number this pull request is fixing**

Closes #

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

### CODE REVIEW

**Comment by santoshshanbhogue** [comment]
HI @ischoegl  are you using any special flags to build Cantera from source on MacOS M1? Because when I try to use cantera with Xcode, it uses Rosetta as the architecture to match the dynamically linked libraries generated by Cantera. I am able to use it just fine, but was curious if I am compiling it the wrong way

**Comment by ischoegl** [comment]
> HI @ischoegl are you using any special flags to build Cantera from source on MacOS M1? Because when I try to use cantera with Xcode, it uses Rosetta as the architecture to match the dynamically linked libraries generated by Cantera. I am able to use it just fine, but was curious if I am compiling it the wrong way

Good question. On my own M2, I am compiling within a conda environment that is built for ARM; I am attempting the same in here via this [setup-miniconda example](https://github.com/marketplace/actions/setup-miniconda#example-13-apple-silicon). It obviously isn't running yet.

*Edit: aborting this attempt - not familiar enough with the GH Actions infrastructure.*

PS: likely forgot a `shell: bash -el {0}` in the setup script, but oh well.

PPS: @santoshshanbhogue ... to answer your question: I just checked about Rosetta and cxx samples compiled on my machine appear to be running natively, i.e. on "Apple" ("kind" in Activity Monitor would otherwise be "PowerPC"). I am sure there are easier ways to check ...

**Comment by bryanwweber** [comment]
@ischoegl hope you don't mind, I'll reopen this and try to get it working this week 😊

**Comment by ischoegl** [comment]
> @ischoegl hope you don't mind, I'll reopen this and try to get it working this week 😊

Thanks - no problem whatsoever!

**Pull request closed without merging**
