### PR TITLE
Update flame1.m

### PR DESCRIPTION
**Pull request by arjavvashi**
Please fill in the issue number this pull request is fixing:

Fixes # Typo in a comment.

Changes proposed in this pull request:
- Removed a typo in the help section in the beginning of the code
-
-

### CODE REVIEW

**Comment by speth** [comment]
I'm not sure that this is a typo. For better or worse, most of the Matlab examples contain the line `help <examplename>`, but none of them have this built-in pause. My inclination would be to delete this commented-out code rather than to execute it.

The same applies to `catcomb.m` as well.

**Comment by arjavvashi** [comment]
I agree with you @speth. The comment should be removed altogether

**Comment by speth** [comment]
Feel free to push a commit to this PR resolving the issue in that way, then (preferably for both affected files).

**Comment by CyberDrudge** [comment]
@arjavvashi are you still working on this or should i update the files?

**Comment by speth** [comment]
Superseded by #627.

**Pull request closed without merging**
