### PR TITLE
Fix #1525

### LINKED ISSUE #1525: Make pint optional when running tests
**Problem description**

The use of the Pint units library within the Cantera Python module is optional. However, attempting to run the Python test suite without Pint installed fails.

This is dissimilar to how we handle testing of other optional dependencies in Python, where we are able to use the `@pytest.mark.skipif` decorator.

**Steps to reproduce**

1. Set up a Cantera build environment including all Python dependencies, but not including Pint
2. Run `scons test`

**Behavior**

```
___________________________________________ ERROR collecting test_units.py ___________________________________________
ImportError while importing test module '/root/cantera/test/python/test_units.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/python/test_units.py:7: in <module>
    import cantera.with_units as ctu
build/python/cantera/with_units/__init__.py:7: in <module>
    from pint import UnitRegistry, set_application_registry
E   ModuleNotFoundError: No module named 'pint'
```

**System information**

- Cantera version: 3.0.0b1
- OS: Debian 11 (Bullseye)
- Python/MATLAB/other software versions: Python 3.9

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

Avoid test failures if optional `pint` package is not found

**If applicable, fill in the issue number this pull request is fixing**

Closes #1525

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Review by speth — APPROVED** [review]
Thanks, @ischoegl. That's simpler than I thought it would be!

**Comment by bryanwweber** [comment]
Is pint tested anywhere on CI still after these removals?

**Comment by speth** [comment]
Yes, if you look at `main.yaml`, you will see that it is still installed for almost all of the runners. The cases it is removed from represent ~7 of the ~40 CI runs (and we weren't even running the tests that use `pint` for the various Sundials versions anyway).

**Comment by bryanwweber** [comment]
Thank you! I didn't check, sorry

**Comment by ischoegl** [comment]
> Thanks, @ischoegl. That's simpler than I thought it would be!

@bryanwweber’s comment on #1525 was key ..

**Pull request merged**
