### PR TITLE
1 d continuation

### PR DESCRIPTION
**Pull request by axbriones**
Please fill in the issue number this pull request is fixing:

Fixes #534 

Changes proposed in this pull request:
- One dimensional continuation techniques (one- and two-point) 
-
-

### CODE REVIEW

**Comment by axbriones** [comment]
@speth I created this new pull request based on the 1D continuation that I grabbed for you. Part of the problem is my lack of expertise with version tracking software. Please let me know if we can continue working with #541 and then we can close #534. On another note I added a continuation test in test_onedim.py. This test works fine on my laptop. However, when I tried to execute it I don't think execution ever happened. could you also provide to comments to f12a2ff

**Comment by axbriones** [comment]
@speth Here is a version of the test for the one dimensional continuation method.  There is a conflict, why is this?

**Comment by speth** [comment]
I fixed the merge conflict, which was caused by the fact that both a change to `master` and this PR modified the very end of `test_onedim.py` -- not a big deal, but also not something that Git can figure out on its own.

However, I think most of the comments that I previously made on this set of changes in the previous PR (#534) still need to be addressed. Also note that a unity Lewis number transport model has been added (see #510), so it is not necessary to implement that feature as part of this PR.

**Review by speth — CHANGES_REQUESTED** [review]
When running the test added here (after fixing the path to the `h2o2.cti` file), I get the output:
```
test_diffusion_flame_cont (cantera.test.test_onedim.TestOneDimNumCont) ... Start flamelet generation of FPV type
 Precalculations
  Pressure      Tmax Fuel_mdot
  101325.0     3095.4       0.10
     #n      Tmax       Amax         dT     branch   FlameControl?   # gridpoints
     1     3094.9      131.7      20.00      upper      False           85
     2     3093.0      327.7      20.00      upper      False           87
     3     3090.1      652.1      20.00      upper      False           91
     4     3084.9     1134.8      20.00      upper      False           94
     5     3077.0     1805.4      20.00      upper      False           95
     6     3066.5     2692.6      20.00      upper      False           95
     7     3051.8     3824.2      20.00      upper      False           97
     8     3032.1     5227.0      20.00      upper      False           97
     9     3008.9     6910.7      20.00      upper      False           99
     #n      Tmax       Amax         dT     branch   FlameControl?   # gridpoints
    10     2981.0     8929.0      20.00      upper      False          100
False True False True 2664.53392123918 37 2703.1656996269094 52
Calculation failed; the new value of dT is 10.000000
False True False True 2674.53392123918 37 2713.165699626909 52
Calculation failed; the new value of dT is 5.000000
False True False True 2679.53392123918 37 2718.165699626909 52
Calculation failed; the new value of dT is 2.500000
False True False True 2682.03392123918 37 2720.665699626909 52
Calculation failed; the new value of dT is 1.250000
False True False True 2683.28392123918 37 2721.915699626909 52
Calculation failed; the new value of dT is 1.000000
    11      300.0   819517.4       1.00      lower      False          100
```
which suggests that at least for this example, it is unable to find solutions along the middle branch. Can we at start with an example that actually exercises the the control algorithm working in each branch? I think this issue needs to be resolved before we put any effort into modifying things so that this fits nicely with Cantera's existing code.

**Comment by wandadars** [comment]
@speth Two questions.

A.)  If this PR gets out-of-date a bit with respect to changes on the main cantera master branch, what would be the best way for me to set up a clone of this repo so that I could create a new PR with changes? Something like this?
1.) Clone this repo
2.) Push the 1D-continuation branch up to my cantera fork
3.) Create new PR?

B.) I'm trying to replicate the error that you posted most recently. This is what I'm doing:
1.) Create conda environment with necessary cantera dependencies
2.) Clone the repo by @axbriones and checkout the 1D-continuation branch
3.) scons build python_package=full prefix=<blahBlah/cantera_1D_continuation_build
4.) scons test  (but this runs all the tests and takes several minutes)

If I go into build/python2/cantera/test and run: python test_onedim.py , I get import errors (which I'm pretty sure are because that is not how the tests are supposed to be run).

**Comment by bryanwweber** [comment]
@wandadars Regarding the tests, you can run just the Python tests by

    scons test-python

My suggestion to bring this PR up-to-date is to rebase it onto the current master branch. The following code will checkout a new branch with the existing changes:
```
git checkout -b axbriones-1D-continuation master
git pull https://github.com/axbriones/cantera.git 1D-continuation
```
Then, assuming that you have Cantera/cantera as a remote named `upstream`, you can do
```
git fetch upstream
git rebase upstream/master
```
Most likely this will cause merge conflicts that you'll have to fix.

**Comment by speth** [comment]
I'm a little torn on the best way to move forward here. Normally, I would agree with Bryan's suggestion of rebasing onto the current master and fixing the conflicts where they occur. However, given that the code doesn't work as-is, I'd hesitate to suggest investing time on dealing with resolving merge conflicts while untangling the commit history (which risks introducing new bugs) before seeing if you can get this code working. On the other hand, the rebase will just become harder as you do more work on this branch.

To just run the tests of the 1D solver, you can run `scons test-python2-onedim`. You can also run just a specific test, outside of SCons after running `scons build`. It should be something like
`PYTHONPATH=build/python2 python -m unittest -k TESTNAMEPATTERN cantera.test`.

**Comment by bryanwweber** [comment]
@speth Is the reason you're suggesting `test-python2-onedim` because this code is based before the removal of Python 2 support? Would it be better to run `test-python3-onedim` until it is rebased and then just `test-python-onedim` after?

**Comment by axbriones** [comment]
@speth @bryanweber Hello, sorry that I've out of the loop for a while. I'm planning to start working in this project again in about two weeks .

**Comment by speth** [comment]
@bryanwweber I mentioned Python 2 because @wandadars specified that path in his message. Running the tests with Python 3 would be slightly preferable, but is well behind the two major issues that need to be resolved here.

**Comment by ischoegl** [comment]
Superseded by #766 via #759 - closing.

**Pull request closed without merging**
