### PR TITLE
[CI] Update CI workflow

### LINKED ISSUE #944: Sundials CI failure for python:test_kinetics.KineticsRepeatability.test_pdep_err
**Problem description**

CI test for `python:test_kinetics.KineticsRepeatability.test_pdep_err` fails for Sundials runners. All other tests are successful. 

Issue was observed while testing #943 - which presumably does not affect Kinetics.
 
**Steps to reproduce**

Presumably any newly created PR will trigger this issue.

**Behavior**

```
======================================================================
FAIL: test_pdep_err (cantera.test.test_kinetics.KineticsRepeatability)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cantera/cantera/build/python/cantera/test/test_kinetics.py", line 419, in test_pdep_err
    ct.Solution('addReactions_err_test.yaml')
cantera._cantera.CanteraError: 
***********************************************************************
CanteraError thrown by addReactions:

***********************************************************************
CanteraError thrown by Plog::validate:

Invalid rate coefficient for reaction 'CH2CHOO <=> CH3O + CO'
at P = 32019, T = 500

Invalid rate coefficient for reaction 'CH2CHOO <=> CH3O + CO'
at P = 32019, T = 1000

Invalid rate coefficient for reaction 'CH2CHOO <=> CH3O + CO'
at P = 1.0132e+05, T = 500

Invalid rate coefficient for reaction 'CH2CHOO <=> CH3O + CO'
at P = 1.0132e+05, T = 1000
***********************************************************************

***********************************************************************
CanteraError thrown by Plog::validate:

Invalid rate coefficient for reaction 'CH2CHOO <=> CH3 + CO2'
at P = 1.0132e+07, T = 500
***********************************************************************

***********************************************************************
InputFileError thrown by Kinetics::checkReactionBalance:
Error on line 126 of /home/runner/work/cantera/cantera/build/python/cantera/test/data/addReactions_err_test.yaml:
The following reaction is unbalanced: H2O2 + OH <=> 2 H2O + HO2
  Element    Reactants    Products
  H           3           5
  O           3           4

|  Line |
|   121 | - equation: CH2CHOO <=> CO2 + CH3  # Reaction 2
|   122 |   type: pressure-dependent-Arrhenius
|   123 |   rate-constants:
|   124 |   - {P: 100.0 atm, A: -2510.0, b: 1.41, Ea: 1.442e+04}
|   125 |   - {P: 100.0 atm, A: 4.05e-09, b: 5.14, Ea: 1.048e+04}
>   126 > - equation: H2O2 + OH <=> 2 H2O + HO2  # Reaction 3
            ^
|   127 |   rate-constant: {A: 1.0e+13, b: 0.0, Ea: 1800.0}
***********************************************************************
***********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/cantera/cantera/build/python/cantera/test/test_kinetics.py", line 424, in test_pdep_err
    self.assertIn(msg, err_msg_list)
AssertionError: 'at P = 32019, T = 500.0' not found in ['', '***********************************************************************', 'CanteraError thrown by addReactions:', '', '***********************************************************************', 'CanteraError thrown by Plog::validate:', '', "Invalid rate coefficient for reaction 'CH2CHOO <=> CH3O + CO'", 'at P = 32019, T = 500', '', "Invalid rate coefficient for reaction 'CH2CHOO <=> CH3O + CO'", 'at P = 32019, T = 1000', '', "Invalid rate coefficient for reaction 'CH2CHOO <=> CH3O + CO'", 'at P = 1.0132e+05, T = 500', '', "Invalid rate coefficient for reaction 'CH2CHOO <=> CH3O + CO'", 'at P = 1.0132e+05, T = 1000', '***********************************************************************', '', '***********************************************************************', 'CanteraError thrown by Plog::validate:', '', "Invalid rate coefficient for reaction 'CH2CHOO <=> CH3 + CO2'", 'at P = 1.0132e+07, T = 500', '***********************************************************************', '', '***********************************************************************', 'InputFileError thrown by Kinetics::checkReactionBalance:', 'Error on line 126 of /home/runner/work/cantera/cantera/build/python/cantera/test/data/addReactions_err_test.yaml:', 'The following reaction is unbalanced: H2O2 + OH <=> 2 H2O + HO2', '  Element    Reactants    Products', '  H           3           5', '  O           3           4', '', '|  Line |', '|   121 | - equation: CH2CHOO <=> CO2 + CH3  # Reaction 2', '|   122 |   type: pressure-dependent-Arrhenius', '|   123 |   rate-constants:', '|   124 |   - {P: 100.0 atm, A: -2510.0, b: 1.41, Ea: 1.442e+04}', '|   125 |   - {P: 100.0 atm, A: 4.05e-09, b: 5.14, Ea: 1.048e+04}', '>   126 > - equation: H2O2 + OH <=> 2 H2O + HO2  # Reaction 3', '            ^', '|   127 |   rate-constant: {A: 1.0e+13, b: 0.0, Ea: 1800.0}', '***********************************************************************', '***********************************************************************']

----------------------------------------------------------------------

```

**System information**

- Cantera version: 2.5.0b1 `main`
- OS: Sundials CI runner
- Python/MATLAB/other software versions: N/A

### PR DESCRIPTION
**Pull request by bryanwweber**
**Changes proposed in this pull request**

- Version bumps of dependencies in the CI workflow
- Fix location of Boost libraries on Windows
- Add tests on Python 3.9 and Ubuntu 20.04
- Add format specification in Pdep error printout

**If applicable, fill in the issue number this pull request is fixing**

Fixes #944

**Checklist**

- [X] There is a clear use-case for this code change
- [X] The commit message has a short title & references relevant issues
- [X] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [X] The pull request is ready for review

### CODE REVIEW

**Comment by ischoegl** [comment]
#944 is still there ... no idea what’s causing that.

**Comment by bryanwweber** [comment]
Yeah, seems to be something specific to the Conda-Forge SUNDIALS installations. Probably have to debug it locally.

On the plus side, no problems with Python 3.9!

**Comment by speth** [comment]
I opened #947 to fix #944, but didn't realize that there were other things breaking the CI. I think adding my commit from that PR to this one should put us back into business.

**Comment by bryanwweber** [comment]
There are some changes here which are also in https://github.com/Cantera/cantera/pull/641/commits/68dee9276da49d776a1aef5a3404884135d9493c in #641. Presumably #641 will need to be rebased to drop the commit I pushed to Gandhali's branch once this is merged.

**Comment by ischoegl** [comment]
:tada: ... looks like CI is back! Are there any other updates planned under this PR?

**Comment by bryanwweber** [comment]
No, I think this is ready to merge!

**Comment by ischoegl** [comment]
:+1: ... Excellent - I rebased #949 (which is a trivial fix), #936/#931/#907 (which should be ready after being reviewed by @speth last weekend again), and #921 (not sure about the eventual fate). I don't have any other plans for the moment (I'll still fix trivial issues if they come up and pique my interest - especially if they are based on things I implemented over the last 1 1/2 years).

**Pull request merged**
