### PR TITLE
Add mechanism printers

### PR DESCRIPTION
**Pull request by parkerclayton**
Hi everyone. I've been working on some code that will write a solution object to a mechanism file. Right now, they're independent files stored in `interfaces/cython/cantera`. 

Based on some suggestions from Brian Weber I'm working on a cleaner integration of this code using existing classes to gather the information, but for now I wanted to share what I have. Any suggestions or comments are welcome!

### CODE REVIEW

**Comment by bryanwweber** [comment]
@parkerclayton Thanks for putting this code into the main repo here. I think my suggestions from earlier about integrating this into the `Solution`, `Species`, `Reaction` classes, etc. would be super helpful, rather than having standalone scripts. It would be great to make each class aware of how to print itself into the various formats.

**Comment by speth** [comment]
While I think I previously advocated for the same level of integration that Bryan is suggesting, given the plans for replacing the CTI format in the relatively near future, I think keeping the Solution-to-CTI writer as a separate script makes the most sense. I also think there's something nice about keeping anything to do with the Chemkin format separate from the actual Cantera classes.

One thing that I would recommend with this PR is that it might be helpful to clean up the history by rebasing this onto the current master and squashing some of the commits to eliminate the merge commits and churn associated with commits that are just fixing formatting / typos / etc. in previous commits.

**Comment by bryanwweber** [comment]
@speth Any reason why these shouldn't be integrated? I don't immediately see a reason that introducing the new format makes it less worthwhile that these should be integrated. I can foresee cases where having each class aware of how to print to various formats would be useful, for instance, if one is constructing a mechanism on the fly by including various `Species` etc objects.

Even if the basic functionality is accepted as standalone scripts here, I think the long-term goal should be integration into the existing classes.

**Comment by speth** [comment]
I expect the coming new format will mean the deprecation of the CTI format, so I don't think it's worth a major refactoring of this code for something that won't be part of the code base in the long term. In addition, I'm expecting the integrated mechanism output to the YAML format will need to be implemented at the C++ level in any case so that it's available from all interfaces, so modifying this to more tightly integrate it wouldn't even serve as a pattern for the YAML serializer.

The other benefit of this standalone approach is that it's something that people can be pointed to right now, without having to upgrade to an unreleased version of Cantera.

**Comment by ischoegl** [comment]
@speth and @bryanwweber  ... while I do see that the upcoming deprecation of CTI/XML will affect this work, I do believe that @parkerclayton did contribute something very useful, i.e. there deserves to be an equivalent in the new YAML format.

**Comment by ischoegl** [comment]
Superseded by #1185.

**Pull request closed without merging**
