### PR TITLE
Fix Typo

### LINKED ISSUE #590: Typo in Matlab cp_mass documentation
### Cantera version
2.4.0

The documentation for the `cp_mass` function in the Matlab toolbox is incorrect, it reads

```matlab
% :return:
%     Molar basis specific heat of the mixture at
```

To correct this, the file at [`interfaces/matlab/toolbox/@ThermoPhase/cp_mass.m`](https://github.com/Cantera/cantera/blob/master/interfaces/matlab/toolbox/%40ThermoPhase/cp_mass.m) needs to be edited, and the other similar files that distinguish mass- or molar-basis should be checked for consistency.

As reported by email by Qiang Zhange.

### PR DESCRIPTION
**Pull request by CyberDrudge**
Fixes #590

### CODE REVIEW

**Comment by bryanwweber** [comment]
@CyberDrudge Did you check that this was the only place where this typo occurred? Thanks!

**Comment by CyberDrudge** [comment]
Yes, I checked the relevant files and they were all good.

**Comment by bryanwweber** [comment]
@CyberDrudge Now that your other PR is merged, can you please rebase this change onto the most recent master commit and remove the merge commit?

**Comment by CyberDrudge** [comment]
@bryanwweber i force pushed my changes after doing a git rebase but it looks like i messed up. 

**EDIT**: I rebased the branch without pulling updates from upstream. Rebasing again after pulling upstream seems to fix this.

**Comment by CyberDrudge** [comment]
_Sigh!_ I guess this fixes things.

**Comment by bryanwweber** [comment]
Thanks @CyberDrudge

**Pull request merged**
