### PR TITLE
Speed up CI tests

### PR DESCRIPTION
**Pull request by speth**
**Changes proposed in this pull request**

- Allow a subset of "slow" tests to be disabled, and use this on the "coverage" CI runs. Mechanisms for this are introduced for Python tests, gtest tests, and the "test_problems" regression tests.
- Speed up some tests by switching from CTI inputs to YAML
- Avoid creating unnecessary `Transport` objects during tests that use `gri30` and `h2o2` mechanisms.

**Checklist**

- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by ischoegl** [comment]
Great to see some of this moving along! One question I had was about replacing `kineticsFromScratch.cti` in `kineticsFromScratch.cpp` (which has come up in #995). Conversion to YAML isn't the issue here (file is already in #995), but setting up the objects has created some double-free's (?) that I am unable to track down (`gdb`, `valgrind` and all). There's a parallel implementation in `kineticsFromScratch3.cpp` that uses the new framework ...

**Comment by speth** [comment]
> 
> 
> Great to see some of this moving along! One question I had was about replacing `kineticsFromScratch.cti` in `kineticsFromScratch.cpp` (which has come up in #995). Conversion to YAML isn't the issue here (file is already in #995), but setting up the objects has created some double-free's (?) that I am unable to track down (`gdb`, `valgrind` and all). There's a parallel implementation in `kineticsFromScratch3.cpp` that uses the new framework ...

Sorry, I'm not sure I understand the issue as it relates to this PR. Are you saying that if I were to substitute `kineticsFromScratch.yaml` for `kineticsFromScratch.cti` (which I haven't done yet, but would fit within the overall scope of this PR, I suppose), I should be able to see some of these errors?

**Comment by ischoegl** [comment]
> Are you saying that if I were to substitute `kineticsFromScratch.yaml` for `kineticsFromScratch.cti` (which I haven't done yet, but would fit within the overall scope of this PR, I suppose), I should be able to see some of these errors?

Correct. My own attempt in the conversion runs without errors, but the `gtest` doesn't shut down properly. I am likely overlooking something in the way I set up my objects. It's the first issue in a long time that leaves me stumped. And yes, I was hoping that it would fit into the scope of this PR :wink:

**Comment by ischoegl** [comment]
Would it be possible to add d3ee682f364c5599c2cfa70704cda52e4743079e as a separate PR? This part of CI apparently broke yesterday, and it would be good if it were available for anyone else to rebase to.

**Review by ischoegl — APPROVED** [review]
This looks good to me.

**Pull request merged**
