### PR TITLE
Update GitHub documentation and templates

### PR DESCRIPTION
**Pull request by speth**
**Changes proposed in this pull request**

- Update references to the default branch, now named `main`
- Change order of fields in the PR template (put the description of changes above the checklist)
- Revise the Issue template to emphasize providing the "steps to reproduce" and deemphasize describing "expected behavior" (which I felt encouraged unintentionally abrasive and unhelpful problem descriptions akin to "the program runs and does not crash").

**Checklist**

- [X] There is a clear use-case for this code change
- [X] The commit message has a short title & references relevant issues
- [X] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [X] The pull request is ready for review

### CODE REVIEW

**Comment by bryanwweber** [comment]
These changes should probably also be made in `.github/workflows/main.yml`, although the CI appears to have run anyways...

**Comment by ischoegl** [comment]
@speth ... :+1: on the template change.

However, I’m not sure why you’d like to change away from a customary nomenclature that is commonly used by `git`. I am afraid that this will be confusing for any new contributor who is unfamiliar with `git`. Most online resources will reference a `master` branch ...

**Comment by ischoegl** [comment]
:+1: ... [context](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/)

**Comment by speth** [comment]
Did I miss something? There are several changes to `.github/workflows/main.yml` in this PR. I guess the only thing that doesn't reflect this is the PR title...

**Comment by ischoegl** [comment]
CI is no longer triggered after pushing changes to branches previously set up to be merged into master ... see current status of #888

**Comment by bryanwweber** [comment]
@speth Sorry, I must have missed the changes before I commented!

@ischoegl That's not unexpected, the CI is only triggered for pull requests to `master`, but the PRs are going to `main` now. This PR should fix that.

**Review by bryanwweber — APPROVED** [review]

**Comment by ischoegl** [comment]
@bryanwweber ... :+1: confirmed. I was just puzzled as CI had been triggered on this PR (which I assumed was after the renaming).

**Comment by bryanwweber** [comment]
@ischoegl I'm guessing caching (it's always caching 😄 )

**Pull request merged**
