### PR TITLE
Assorted C++ / SCons cleanup

### PR DESCRIPTION
**Pull request by speth**
**Changes proposed in this pull request**

- Update check for Boost to specify 1.70 as minimum version
- Use `FMT_HEADER_ONLY` only for platforms and fmt versions where necessary (revises fix for #1540)
- Fix reporting Eigen version during build process
- Clean up spacing around angle brackets in templates, e.g. change `vector<vector<double> >` to `vector<vector<double>>`
- Deprecate unused `begin()` / `end()` methods of matrix classes
- Remove vestigial `ReactorSurface` data from `WallBase`
- Keep conda build environment path out of generated `cantera.pc`
- Skip pint-based tests for pint<0.17.0, where the test helpers aren't available

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Review by ischoegl — APPROVED** [review]
Looks good to me!

**Comment by ischoegl** [comment]
PS: Regarding the removal of `ReactorSurface` from `Wall` it may be worth revisiting in the future.

**Comment by speth** [comment]
> PS: Regarding the removal of `ReactorSurface` from `Wall` it may be worth revisiting in the future.

I don't think so. The only thing that `Wall` and `ReactorSurface` have in common is that they both have an area. `Wall` objects represent interactions between two reactors, while `ReactorSurface` objects represent heterogeneous kinetics in a single reactor. Separating these capabilities led to a significant simplification in setting up networks with `ReactorSurfaces`, since you don't need to define a separate `Reactor` or `Reservoir` to insert the wall between just to be able to add a reacting surface.

**Comment by ischoegl** [comment]
I guess I misspoke: it's actually `WallBase` I had in mind, see [doxygen wallGroup](https://cantera.org/documentation/dev/doxygen/html/d0/d2d/group__wallGroup.html). While this may still not make sense, there's also this old issue that we may be able to resolve at some point ... https://github.com/Cantera/enhancements/discussions/92

**Pull request merged**
