### PR TITLE
Exporting Jupyter notebook examples as py modules and moving to examples

### PR DESCRIPTION
**Pull request by decaluwe**
For the `reactor` examples in the Jupyter notebook demos, exporting the
resulting python modules as .py files and moving to
interfaces/cython/cantera/examples/.

### CODE REVIEW

**Comment by speth** [comment]
I'm wondering what the motivation for this is.

I think it's worth having two different sets of examples, with some distinctions between the two. In my mind, the difference is that the examples in the Cantera repository are there mainly to demonstrate features of the different models within Cantera, while the Jupyter examples can be more complex applications of the models, which rely on additional input data and demonstrate linkage with other packages.

Two specific concerns I have:
- Duplication of examples is a maintenance burden when there is a desire to update either one
- I don't really want the Cantera source code repo to become a warehouse for mechanism files, especially large ones (the Galway mechanism weighs in at 1.7 MB).

**Comment by decaluwe** [comment]
Hi Ray,

That's fair; in my mind, there are two main motivations:
1. Different user types will prefer a Jupiter notebook vs just looking at the python code. To me the distinction b/t the two is that someone less familiar with coding and executing a python module would be more comfortable getting their feet wet via a notebook. 

2. I'm of the mind that more examples  are generally better. People downloading Cantera are not necessarily aware of the notebook repository, so this gives them another location to find the demonstrations. 

That said, I'm sensitive to both your concerns, below. I think there is value, however, in having a real gas reactor example in there. 

How about if I remove the other two examples, and then modify the real gas shock tube to reduce the extra dependencies (I.e. Pandas and anything else that may be in there)?

Steven

**Comment by speth** [comment]
I'd certainly happy to see a simpler real gas example added to the main repo -- would you see any real gas effects if you just added the Redlich-Kwong coefficients to the h2o2 mechanism that's already in the repo? That would constitute a nice minimal example, if so. Otherwise, adding the mechanism from that Jupyter example is OK. More distinct examples is definitely good, so I would think the current Jupyter example should remain as-is.

I would assume that more advanced users either know how to convert the Jupyter notebooks to regular python scripts, or would just copy code out of them if they wanted to. The notebook examples are linked from the main Cantera documentation, but maybe there are other places that we should point people to those examples as well. I'm open to suggestions on that front.

**Comment by decaluwe** [comment]
Okay, sounds good.  Let me check on the real-gas effects using the h2o2 mech.

**Comment by decaluwe** [comment]
So there is a very small real gas effect for the h2o2 mech, in terms of the IDT - on the order of 2% This is not terribly surprising: real gas effects very generally scale with molecular weight, and the h2o2 mech species are generally pretty small (h2o2 is the largest molecule, there).

However, I checked over a range of pressures, and there is no observable NTC behavior to speak of, for either ideal gas or real gas.

I guess my preference would be to keep the Wang et al. mechanism - it better shows the real gas IDT effect, and allows demonstration of the NTC behavior.  

The py file needs to be cleaned up a bit, though, and I'll add some features to more generally highlight the real gas effects.

**Comment by decaluwe** [comment]
Alright, somebody help me out: what does this mean?

**Comment by skyreflectedinmirrors** [comment]
@decaluwe basically that the unittests will cover slightly more of Cantera's codebase (probably a good thing)

**Comment by decaluwe** [comment]
Okay, thanks - but then the Travis CI build failed.  I do not know what that is, nor how to fix it…

**Comment by bryanwweber** [comment]
@decaluwe TravisCI is the continuous integration for Linux and macOS. It automatically runs the test suite for every commit that gets pushed to GitHub and makes sure everything passes. It failed for your commit because the tests took too long and exceeded the time limit that Travis sets. Someone has already restarted it, so we just have to wait and see what happens. I'll be interested to see what's taking longer now and causing it to error, and also why Linux failed but macOS passed.

**Comment by speth** [comment]
I don't know why Travis has been so slow lately. Obviously, since this PR only adds an example that doesn't get executed as part of the test suite, it shouldn't affect anything (and the claimed change in test coverage is also spurious, and related to some earlier commits of mine).

**Comment by decaluwe** [comment]
Thanks for the clarifications, everyone. I was starting to doubt my sanity - I couldn't figure out how adding an example would change the coverage or the build process!

**Comment by decaluwe** [comment]
Okay, looks like the Travis build went through fine, this time.

**Comment by decaluwe** [comment]
Ray - can I get this merged and closed?  Would like to move on to some other PRs, and prefer to keep the # of disparate branches on my local fork to a min (simply to help shield me from my own Git ineptitudes).

**Comment by speth** [comment]
Steven, sorry for the delay. I had been waiting for the update to compare the real and ideal gas cases, and missed that you had already done that :grimacing: 

Where do the R-K coefficients in the mechanism come from? There's a reference to a paper by Kogekar et al. in the Jupyter notebook that this example originated from, but I can't seem to find that paper. I think this should be documented in the mechanism file.

I'd also like to remove the pandas dependency (mainly using `SolutionArray` instead). I'd be happy to make that change if you don't mind.

**Comment by decaluwe** [comment]
Okay, thanks.  The Kogekar et al. paper is in press, but I'll add some documentation to explain the R-K constant calculations.

**Comment by decaluwe** [comment]
Okay, should be good now.  Added documentation and then squashed commit into previous commit.

Ray, if it isn't too much trouble to replace the Pandas dependency, I'd appreciate it.  Otherwise, I can figure out how to do it.

Thanks.

**Pull request merged**
