### PR TITLE
[SCons] Copy missing yaml input to LiC6_electrode sample

### LINKED ISSUE #774: Fix examples in `samples` folder
Please fill in the following information to report a problem with Cantera.
If you have a question about using Cantera, please post it on our
[Google Users' Group](https://groups.google.com/forum/#!forum/cantera-users).

**System information**

- Cantera version: 2.5.0a3 (master branch)
- OS: Linux
- Python/MATLAB version: N/A

**Expected behavior**

All samples work without errors/warnings.

**Actual behavior**

One sample fails (missing input file)
```
$ ./LiC6_electrode 

***********************************************************************
CanteraError thrown by Application::findInputFile:

Input file LiC6_electrodebulk.xml not found in directories 
'.', 
'/usr/local/share/cantera/data'

To fix this problem, either:
    a) move the missing files into the local directory;
    b) define environment variable CANTERA_DATA to
         point to the directory containing the file.
***********************************************************************
```
and another raises a warning (issue caused by PR #632)
```
$ ./combustor 
DeprecationWarning: FlowDevice::setMassFlowRate(): To be removed after Cantera 2.5. Use device-specific functions (e.g. Valve::setValveCoeff) instead.
DeprecationWarning: Valve::setParameters(): To be removed after Cantera 2.5. Use Valve::setValveCoeff instead.
```

**To Reproduce**

1. Compile cantera from master (e.g. c4c30e3)
2. Run `scons samples`
3. Run examples in `build/samples`

### PR DESCRIPTION
**Pull request by ischoegl**
**Checklist**

- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [x] Build passes (`scons build` & `scons `~`test`~`samples`) and ~unit tests address code coverage~ example works
- [x] The pull request is ready for review

**If applicable, fill in the issue number this pull request is fixing**

Fixes #774

**Changes proposed in this pull request**

- copy missing `LiC6_electrodebulk.yaml` file to sample folder

**PS:** a simpler solution would be to simply move the YAML file to the data folder, which would allow for similar examples to be implemented in Python/Matlab.

### CODE REVIEW

**Comment by bryanwweber** [comment]
Thanks for catching this @ischoegl, I think this is a fine solution.

Re your postscript: As part of #768, I was wondering what we should do with input files that are used for examples. Having them in the `data` folder implies some strong level of endorsement by Cantera, IMO, since the name `data` implies (to me) that the contents are some fundamental data that you need to use for modeling. As such, I was considering whether it would make sense for some of the files there (e.g., `nDodecane_Reitz.yaml`) to move out of the `data` folder and just live with their relevant example scripts, while things like `elements.xml` or `critProperties.xml` (or their converted equivalents) could stay in `data`.

This is complicated for examples in multiple interfaces though, but I think it deserves some discussion. Probably that discussion should not happen in an arbitrary PR though, but in a dedicated issue on our spanky new repo for just such discussions 😃

**Comment by ischoegl** [comment]
@bryanwweber ... thanks for the comments. I agree on the issue of trying to not endorse input data, and instead imply that they serve for illustration purposes, I.e. leave things in the example folder whenever possible.

**Comment by bryanwweber** [comment]
See Cantera/enhancements#22

**Comment by ischoegl** [comment]
> See [Cantera/enhancements#22](https://github.com/Cantera/enhancements/issues/22)

From that perspective, my solution in this PR is only a band-aid ... a better solution would automatically copy any YAML file that is encountered. Will have another look at `SConstruct`

**PS:** will wait for resolution of @speth’s comment regarding convenience of the `data` folder in [Cantera/enhancements#22](https://github.com/Cantera/enhancements/issues/22)

**Comment by ischoegl** [comment]
Following up on @speth's comment in Cantera/enhancements#22, I added a description to clarify the intent of the input file and moved it to the data folder as an alternative option. 

~Depending on the outcome, either d771f83329ed547e2cf6c38e6d4c55d513648bd9 or 0c0b8b4f1834a242b0eca0a3ca4966188d122a5d should be dropped before merging.~ **Edit:** I removed the band-aid fix in `SConstruct`.

**Comment by ischoegl** [comment]
Closing as PR is superseded by discussion in Cantera/enhancements#22

**Comment by ischoegl** [comment]
Reopening as this is a simple fix as the time frame for Cantera/enhancements#22 is unclear.

**Comment by ischoegl** [comment]
@speth and @bryanwweber ... I ended up moving the input file to the generic data path without adding clutter to `SConstruct`. 

At this point, this is a minimal fix that closes #774. I'm not sure whether Cantera/enhancements#22 will make it into 2.5.0.

**Pull request closed without merging**
