### PR TITLE
Make gri30 consistent with latest online version

### LINKED ISSUE #713: Different from official gri30 mechanism
Hi,

It seems that the gri30 mechanism shipped by Cantera is different from the official one at 

[gri30](http://combustion.berkeley.edu/gri-mech/version30/files30/grimech30.dat)

in terms of reaction 296/297. The pre-factor A have been multiplied by two in Cantera version. Any idea?

https://github.com/Cantera/cantera/blob/265a1860cc6d7e2f7dbdbe2128aac585d85c9f7d/data/inputs/gri30.cti#L2016-L2021

### PR DESCRIPTION
**Pull request by ischoegl**
Please fill in the issue number this pull request is fixing:

Fixes #713

Changes proposed in this pull request:
- Use latest versions of kinetics/thermo files
- The update keeps input and thermo  files separate (i.e. files are identical to online version), which requires minor changes in the build scripts.
- The static `gri30.cti` file is regenerated (with sections for additional phases inserted manually), `gri30_highT.cti` is edited manually, and `gri30_ion.cti` does not require an update.

PS: after removing thermo data, I confirmed that updated GRI3.0 input files indeed only differ in two relevant lines, i.e.
```
$ diff -w grimech30.dat gri30_.inp
1c1
< ! GRI-Mech Version 3.0 7/30/99  CHEMKIN-II format
---
> ! GRI-Mech Version 3.0 3/12/99  CHEMKIN-II format
407,408c407,408
< O+CH3CHO<=>OH+CH2CHO                     2.920E+12     .000    1808.00
< O+CH3CHO=>OH+CH3+CO                      2.920E+12     .000    1808.00
---
> O+CH3CHO<=>OH+CH2CHO                     5.840E+12     .000    1808.00
> O+CH3CHO=>OH+CH3+CO                      5.840E+12     .000    1808.00
```

### CODE REVIEW

**Review by speth — CHANGES_REQUESTED** [review]
Since `gri30.cti` is already a manually-edited file, my suggestion on how to implement this change would have been to make only the minimal edits to `gri30.cti`, rather than fully regenerating it. I think this is especially true given the limited remaining lifespan of `gri30.cti` as we transition to the YAML format.

Similarly, I would suggest leaving the thermo data in `gri30.inp` so that the meaningful difference here (in the rate constants for those two reactions) is clear in the diff rather than being lost in hundreds of other lines of changes.

**Comment by ischoegl** [comment]
> Since gri30.cti is already a manually-edited file, my suggestion on how to implement this change would have been to make only the minimal edits to gri30.cti, rather than fully regenerating it.

:thumbsup: (i.e. done)

> Similarly, I would suggest leaving the thermo data in gri30.inp so that the meaningful difference here (in the rate constants for those two reactions) is clear in the diff rather than being lost in hundreds of other lines of changes.

I think using the original files (as downloaded from [gri-mech/version30](http://combustion.berkeley.edu/gri-mech/version30/files30/grimech30.dat)) allows anyone to quickly verify that the files are identical, which is IMHO more important than keeping a short diff? I had to manually edit the old cantera version before the `diff` generated the expected outcome. I *much* prefer using unmodified files whenever possible (i.e. maintain that part of the PR).

**Comment by speth** [comment]
> I think using the original files (as downloaded from [gri-mech/version30](http://combustion.berkeley.edu/gri-mech/version30/files30/grimech30.dat)) allows anyone to quickly verify that the files are identical, which is IMHO more important than keeping a short diff? I had to manually edit the old cantera version before the `diff` generated the expected outcome. I _much_ prefer using unmodified files whenever possible (i.e. maintain that part of the PR).

That's fair. At least by using the minimally-edited `.cti` file, the changes to those rate constants stand out clearly, even with the other changes, so I think this is fine now.

Can you rebase this onto `master` and fix the conflicts so I can merge it?

**Comment by ischoegl** [comment]
Thanks for the re-review. Hadn't noticed (expected?) a merge conflict, but this shouldn't be hard to resolve.

**Comment by ischoegl** [comment]
Done.

**Review by speth — APPROVED** [review]

**Pull request merged**
