### PR TITLE
[Sphinx/doxygen] Add directives to new/experimental features

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

- Add Sphinx `versionadded` directive to experimental features introduced in Cantera 2.6
- Add `versionadded` without additional information to `Kinetics` derivatives
- Add `@since` directive in corresponding C++ member functions
- ~Address some formatting issues per #1275 (limited to `include/cantera/kinetics` folder)~

See discussion in Cantera/enhancements#150 ... the `versionadded` is selectively applied here to investigate additional Sphinx directives for the generation of API documentation.

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by bryanwweber** [comment]
Thanks for taking a crack at this @ischoegl! I'll look at what this does once all the niggling items from 2.6 are done 😄

**Comment by ischoegl** [comment]
@bryanwweber ... thanks for the feedback! I tried to test this early, as I believe it would be good to discuss before starting to do any serious work towards 3.0 (see Cantera/enhancements#150)

> I'll look at what this does once all the niggling items from 2.6 are done

To me, this is part of it! 😉

**Comment by ischoegl** [comment]
@speth / @bryanwweber ... please let me know.

**Comment by ischoegl** [comment]
Closing - while the application is interesting (and hopefully will be pursued), marking some features as new in 2.6 while not doing the same for others would introduce inconsistencies.

**Pull request closed without merging**
