### PR TITLE
Update code of conduct to version 2.0

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

Update the code of conduct to adopt a newer version provided by the [Contributor Covenant[(https://www.contributor-covenant.org/). The previous version (1.4) was around 5 years old and the new version is more detailed (e.g. impact guidelines).

The only adaptations specific to cantera are the main title, and the e-mail address. At some point, Cantera could be added as an adopter ...

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Review by decaluwe — APPROVED** [review]
Looks great - thanks for recognizing the need to update this and taking care of it, @ischoegl .

**Comment by speth** [comment]
To avoid this going unnoticed, the "code of conduct team" (myself, @bryanwweber, and @kyleniemeyer) should take note of the more detailed enforcement policy that this sets in place. I would have appreciated a chance to at least read this before it got merged.

**Comment by decaluwe** [comment]
Ah, sorry. Good point.

**Comment by kyleniemeyer** [comment]
Yeah, perhaps we need to create a GitHub "team"/group with us on it, and any CoC-related changes/updates could be assigned to us

**Review by kyleniemeyer — COMMENTED** [review]
Looks good to me, though!

**Comment by speth** [comment]
It doesn't look like you can _assign_ an issue/PR to a group, but you can request a review from one. I think it's going to be pretty rare to need to request a review from the CoC team, but perhaps being able to tag the group in a thread would be occasionally useful.

**Comment by ischoegl** [comment]
Sorry guys: I didn’t mean to create a controversy. I honestly didn’t expect this to get merged that quickly!

One thing I noticed is that they encourage to add communities that adopt this covenant to their site using a PR, see [here](https://github.com/ContributorCovenant/contributor_covenant/blob/release/README.md#registering-your-community-as-an-adopter), which I don’t feel comfortable doing myself.

**Comment by decaluwe** [comment]
Honestly, the changes all looked like common sense best practices, and I could think of any reasonable arguments against any of them.

But I agree that I jumped the gun on merging, in that changes like this should still be discussed and officially approved.

**Comment by ischoegl** [comment]
I believe creating a **Cantera/CoC** team is a good idea, as it would be pretty easy to request a review (or give a heads-up as needed)

**Comment by speth** [comment]
I created the team as @Cantera/conduct, for future use as the Code of Conduct bat signal.

**Pull request merged**
