### PR TITLE
doc: hydrogen combustion example blank page removed

### PR DESCRIPTION
**Pull request by vdevgan**
Changes proposed in this pull request:
- "hydrogen combustion reaction " page in doc was empty. 
that has been removed.

### CODE REVIEW

**Comment by bryanwweber** [comment]
This is being tracked in #313, where the solution is to add the example rather than removing the page

**Comment by vdevgan** [comment]
could I be shown another example in the doc or elsewhere to know in what specific format is the example to be filled?

**Comment by bryanwweber** [comment]
The example in question is on pg. 55 of the PDF linked in #313. Other examples can be found in https://github.com/Cantera/cantera/tree/master/interfaces/cython/cantera/examples for Python and https://github.com/Cantera/cantera/tree/master/samples/matlab for Matlab. Note that the script in the PDF is a Matlab script, but we would prefer to have either Python or both Python and Matlab. You can also directly use the `h2o2.xml` file as the chemistry file, rather than a subset of GRI-3.0 as in the PDF.

**Comment by speth** [comment]
I'm inclined to accept the solution of just removing the blank page, since it's not clear that those examples really belong as part of the CTI documentation anyway. The only change needed to this PR is that the entry in `index.rst` also needs to be removed. Issue #313 should remain open as a reminder that those examples have not been migrated.

**Comment by vdevgan** [comment]
combustion example reference from cti/ index.rst has been removed.

**Pull request merged**
